Modify Makefiles to prepare all files before generating manifest
gramineproject/examples pull request #105
Opened 2024-07-30 08:25 UTC by dimakuv

Commit "[LibOS] Move trusted and allowed files logic to LibOS" (currently as PR https://github.com/gramineproject/gramine/pull/1812) in core Gramine repository requires that the generation of the `.manifest` file happens after all executable/test/script files are prepared on the system. This commit adjusts the build system (Makefiles) in this way.

2024-07-30 08:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`iperf/Makefile` line 29 at r1](https://reviewable.io/reviews/gramineproject/examples/105#-O31jq_l4FRX3vFwAGPo:-O31jq_l4FRX3vFwAGPp:b-y2gomv) ([raw file](https://github.com/gramineproject/examples/blob/82b6894e221c8ab4f5d13e9641631def9a245269/iperf/Makefile#L29)):*
> ```Makefile
> 	tar -C $(IPERF_DIR) --strip-components=1 -xf $(IPERF_SRC)
> 
> $(IPERF_DIR)/src/.libs/iperf3 $(IPERF_DIR)/src/.libs/libiperf.so.0: $(IPERF_DIR)/configure
> ```

FYI: Note that `libiperf.so.0` was missing from the pre-requisites. This was a bug.
___
*[`tensorflow-lite/Makefile` line 75 at r1](https://reviewable.io/reviews/gramineproject/examples/105#-O31jxWg9eEvrTxZRbnd:-O31jxWg9eEvrTxZRbne:bl4yo9e) ([raw file](https://github.com/gramineproject/examples/blob/82b6894e221c8ab4f5d13e9641631def9a245269/tensorflow-lite/Makefile#L75)):*
> ```Makefile
> 
> .INTERMEDIATE: sgx_sign
> sgx_sign: label_image.manifest
> ```

FYI: Note that `label_image.manifest` target already has the deleted-from-here two files, so there's no need to re-add these files over there.


<!-- Sent from Reviewable.io -->

2024-08-03 16:26 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/examples/105#-O3O2qSK1_wnMP28Ay5f):*
This doesn't really explain much IMO.
Is this change required because now `gramine-manifest` is hashing all the files, instead of `gramine-sgx-sign`?


<!-- Sent from Reviewable.io -->

2024-08-05 07:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/examples/105#-O3O2qSK1_wnMP28Ay5f):*
Done.

> Is this change required because now `gramine-manifest` is hashing all the files, instead of `gramine-sgx-sign`?

Yes.


<!-- Sent from Reviewable.io -->

2024-08-05 11:13 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`iperf/Makefile` line 29 at r2](https://reviewable.io/reviews/gramineproject/examples/105#-O3XDxvW4ZDrpJnS-qhE:-O3XDxvW4ZDrpJnS-qhF:b-desz2g) ([raw file](https://github.com/gramineproject/examples/blob/e2e0be99ee1f5c7807a9a04eec47a2238461072a/iperf/Makefile#L29)):*
> ```Makefile
> 	tar -C $(IPERF_DIR) --strip-components=1 -xf $(IPERF_SRC)
> 
> $(IPERF_DIR)/src/.libs/iperf3 $(IPERF_DIR)/src/.libs/libiperf.so.0: $(IPERF_DIR)/configure
> ```

I think it doesn't work like that in Make? This defines two recipes (which are the same) for the two targets, but both will run concurrently and destroy each other's results. To define a single recipe which generates two outputs you need "Rules with Grouped Targets" (`&:`) but that's fatally broken on Ubuntu 20.04 and we can't use it until we drop the support for 20.04. See other makefiles.


<!-- Sent from Reviewable.io -->

2024-08-06 06:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`iperf/Makefile` line 29 at r2](https://reviewable.io/reviews/gramineproject/examples/105#-O3XDxvW4ZDrpJnS-qhE:-O3aIA0T406RZarSSSgU:b-pjen9i) ([raw file](https://github.com/gramineproject/examples/blob/e2e0be99ee1f5c7807a9a04eec47a2238461072a/iperf/Makefile#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it doesn't work like that in Make? This defines two recipes (which are the same) for the two targets, but both will run concurrently and destroy each other's results. To define a single recipe which generates two outputs you need "Rules with Grouped Targets" (`&:`) but that's fatally broken on Ubuntu 20.04 and we can't use it until we drop the support for 20.04. See other makefiles.
</blockquote></details>

Done. I guess I was just lucky when trying `make -j` previously on this example...


<!-- Sent from Reviewable.io -->

2024-08-08 01:08 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-08-08 03:06 UTC, kailun-qin requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`iperf/Makefile` line 30 at r3](https://reviewable.io/reviews/gramineproject/examples/105#-O3jjhVs4jaZaSZOKf8z:-O3jjhVs4jaZaSZOKf9-:b-64qj88) ([raw file](https://github.com/gramineproject/examples/blob/b409c5191469896b383735c640ba24e795f59d93/iperf/Makefile#L30)):*
> ```Makefile
> 
> # Make on Ubuntu <= 20.04 doesn't support "Rules with Grouped Targets" (`&:`),
> # see the helloworld example for details on this workaround.
> ```

-> see the helloworld example in the core Gramine repository



_Code quote:_
```Makefile
see the helloworld example
```


<!-- Sent from Reviewable.io -->

2024-08-08 06:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: 3 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @mkow)

___
*[`iperf/Makefile` line 30 at r3](https://reviewable.io/reviews/gramineproject/examples/105#-O3jjhVs4jaZaSZOKf8z:-O3k_GP1E2jSifz-m6ko:buq0mm6) ([raw file](https://github.com/gramineproject/examples/blob/b409c5191469896b383735c640ba24e795f59d93/iperf/Makefile#L30)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> see the helloworld example in the core Gramine repository
</blockquote></details>

Done, thanks, good catch. I fixed it in all example Makefiles now (now this comment is uniform across all Makefiles).


<!-- Sent from Reviewable.io -->

2024-08-08 07:30 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-08-08 12:43 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/105)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-08-08 13:33 UTC, merged