Add note on increasing `vm.max_map_count` for `kmeans_perf_eval.py`
gramineproject/examples pull request #108
Opened 2024-10-10 05:55 UTC by kailun-qin

Linux can return `-ENOMEM` if a request to `mmap()` exceeds the process's maximum number of mappings. This may happen for the `kmeans_perf_eval.py` Scikit-learn example during the checkpoint/restore on the Linux PAL after commit c0a2765
"[LibOS,PAL/Linux-SGX] Add EDMM lazy allocation support". Therefore, `vm.max_map_count` needs to be set to a larger value in such case.

Fixes https://github.com/gramineproject/examples/issues/107.

2024-10-10 17:52 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/108)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/108#-O8rYIDW2QpA_ROa1rjA):*
I would prefer
```
Scikit-learn: Add note on increasing `vm.max_map_count`
```
___
*[`scikit-learn-intelex/README.md` line 64 at r1](https://reviewable.io/reviews/gramineproject/examples/108#-O8rYjAs8WsXo52SNslk:-O8rYjAs8WsXo52SNsll:b-4w7xrv) ([raw file](https://github.com/gramineproject/examples/blob/a3276e17e1ac2b45c0ca5ce7c89b1e054e86d5b3/scikit-learn-intelex/README.md#L64)):*
> ```Markdown
> 
> ```
> sudo sysctl vm.max_map_count=1310720
> ```

Can you add a comment `# the value is just an example`


<!-- Sent from Reviewable.io -->

2024-10-11 06:40 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/108)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/108#-O8rYIDW2QpA_ROa1rjA):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer
```
Scikit-learn: Add note on increasing `vm.max_map_count`
```
</blockquote></details>

Done.
___
*[`scikit-learn-intelex/README.md` line 64 at r1](https://reviewable.io/reviews/gramineproject/examples/108#-O8rYjAs8WsXo52SNslk:-O8uIWqcCkJtSDgaQZBM:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/a3276e17e1ac2b45c0ca5ce7c89b1e054e86d5b3/scikit-learn-intelex/README.md#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment `# the value is just an example`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-11 06:44 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/108)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "squash! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-10-14 15:50 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/108)* status: all files reviewed, 1 unresolved discussion, "squash! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/gramineproject/examples/108#-O9Ahv0WEpAuYRIvYBmf):*




_Suggestion:_
```
[CI-Examples] Scikit-learn
```


<!-- Sent from Reviewable.io -->

2024-10-15 01:28 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/108)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/gramineproject/examples/108#-O9Ahv0WEpAuYRIvYBmf):*
Done.


<!-- Sent from Reviewable.io -->

2024-10-15 07:24 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/108)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/gramineproject/examples/108#-O9Ahv0WEpAuYRIvYBmf):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@mkow @kailun-qin Wait what? This is the Examples repo, it doesn't have `CI-Examples`. This looks wrong, please revert (remove the `[CI-Examples]` prefix).


<!-- Sent from Reviewable.io -->

2024-10-15 07:48 UTC, kailun-qin reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/108)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/gramineproject/examples/108#-O9Ahv0WEpAuYRIvYBmf):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow @kailun-qin Wait what? This is the Examples repo, it doesn't have `CI-Examples`. This looks wrong, please revert (remove the `[CI-Examples]` prefix).
</blockquote></details>

Well, I was a bit confused too but I did see that we have some old commits that have such prefix: https://github.com/gramineproject/examples/commit/553394fcee0f6f878bea19fadb0de6548d824f1a (but I don't know why) ;).

Anyway, I reverted it.


<!-- Sent from Reviewable.io -->

2024-10-15 07:57 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/108)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/gramineproject/examples/108#-O9Ahv0WEpAuYRIvYBmf):*
> Well, I was a bit confused too but I did see that we have some old commits that have such prefix: [553394f](https://github.com/gramineproject/examples/commit/553394fcee0f6f878bea19fadb0de6548d824f1a) (but I don't know why) ;).

True, looks like a bug that went unnoticed. Anyway, approved now.


<!-- Sent from Reviewable.io -->

2024-10-15 11:08 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/108)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 18 at r2](https://reviewable.io/reviews/gramineproject/examples/108#-O9Ahv0WEpAuYRIvYBmf):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Well, I was a bit confused too but I did see that we have some old commits that have such prefix: [553394f](https://github.com/gramineproject/examples/commit/553394fcee0f6f878bea19fadb0de6548d824f1a) (but I don't know why) ;).

True, looks like a bug that went unnoticed. Anyway, approved now.
</blockquote></details>

Ohh, sorry, my bad :)


<!-- Sent from Reviewable.io -->

2024-10-15 11:10 UTC, merged