Add PyTorch Workload Support for Ubuntu 24.04
gramineproject/examples pull request #109
Opened 2024-11-13 06:24 UTC by adarshan-intel

2024-11-14 06:09 UTC, adarshan-intel commented
@mkow @woju Can you review?

2024-12-03 06:05 UTC, kailun-qin requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel)

___
*[`pytorch/Makefile` line 8 at r1](https://reviewable.io/reviews/gramineproject/examples/109#-OD9twnDCO6J9ja0hAQT:-OD9twnDCO6J9ja0hAQU:b-hp0d1h) ([raw file](https://github.com/gramineproject/examples/blob/dad9516c01e00729db7d7b4257fa270089a4e607/pytorch/Makefile#L8)):*
> ```Makefile
> SHELL := /bin/bash
> 
> THIS_DIR := $(shell pwd)
> ```

better to use sth like `$(dir $(lastword $(MAKEFILE_LIST)))`?



_Code quote:_
```Makefile
THIS_DIR := $(shell pwd)
```
___
*[`pytorch/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/examples/109#-ODA2iET5jTkXVgIk0Xi:-ODA2iET5jTkXVgIk0Xj:btx67u9) ([raw file](https://github.com/gramineproject/examples/blob/dad9516c01e00729db7d7b4257fa270089a4e607/pytorch/README.md#L29)):*
> ```Markdown
>   is used by the Makefile.
> - `python3 -m venv my_venv && source my_venv/bin/activate` to create and activate a virtual environment.
> - `pip3 install --user torchvision pillow` to install the torchvision and pillow
> ```

Do we still need this?



_Code quote:_
```Markdown
--user
```


<!-- Sent from Reviewable.io -->

2024-12-03 06:25 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel)

___
*[`pytorch/README.md` line 20 at r1](https://reviewable.io/reviews/gramineproject/examples/109#-ODABV-S6w7kswaMTB21:-ODABV-S6w7kswaMTB22:brtnulh) ([raw file](https://github.com/gramineproject/examples/blob/dad9516c01e00729db7d7b4257fa270089a4e607/pytorch/README.md#L20)):*
> ```Markdown
> # Pre-requisites
> 
> The following steps should suffice to run the workload on a stock Ubuntu 18.04
> ```

what about here?



_Code quote:_
```Markdown
18.04
```


<!-- Sent from Reviewable.io -->

2024-12-03 06:31 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`pytorch/Makefile` line 8 at r1](https://reviewable.io/reviews/gramineproject/examples/109#-OD9twnDCO6J9ja0hAQT:-ODAC8gCDQMcyos8O-om:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/dad9516c01e00729db7d7b4257fa270089a4e607/pytorch/Makefile#L8)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

better to use sth like `$(dir $(lastword $(MAKEFILE_LIST)))`?
</blockquote></details>

Done.
___
*[`pytorch/README.md` line 29 at r1](https://reviewable.io/reviews/gramineproject/examples/109#-ODA2iET5jTkXVgIk0Xi:-ODACBN81_low_OnSzju:bp69lmc) ([raw file](https://github.com/gramineproject/examples/blob/dad9516c01e00729db7d7b4257fa270089a4e607/pytorch/README.md#L29)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do we still need this?
</blockquote></details>

Done. You are right this is not reqd, while testing I removed this flag to install packages, but did not update readme.


<!-- Sent from Reviewable.io -->

2024-12-03 06:34 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: 1 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`pytorch/README.md` line 20 at r1](https://reviewable.io/reviews/gramineproject/examples/109#-ODABV-S6w7kswaMTB21:-ODADWWR33rU9akAke_L:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/dad9516c01e00729db7d7b4257fa270089a4e607/pytorch/README.md#L20)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

what about here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-03 06:51 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-05 05:59 UTC, adarshan-intel commented
@woju @mkow  Please review

2024-12-12 19:18 UTC, mkow requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`pytorch/Makefile` line 9 at r2](https://reviewable.io/reviews/gramineproject/examples/109#-ODwIBzWCjIWzbgKkpHn:-ODwIBzWCjIWzbgKkpHo:b9xqb31) ([raw file](https://github.com/gramineproject/examples/blob/78b83e68e8036b8b8c4c5acb3681f9e001687c36/pytorch/Makefile#L9)):*
> ```Makefile
> 
> THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
> ```

No need for an empty line here
___
*[`pytorch/Makefile` line 11 at r2](https://reviewable.io/reviews/gramineproject/examples/109#-ODwIAAXCx4z6ulwLUax:-ODwIAAXCx4z6ulwLUay:b9xqb31) ([raw file](https://github.com/gramineproject/examples/blob/78b83e68e8036b8b8c4c5acb3681f9e001687c36/pytorch/Makefile#L11)):*
> ```Makefile
> 
> VENV_DIR ?= $(THIS_DIR)/my_venv
> ```

No need for an empty line here


<!-- Sent from Reviewable.io -->

2024-12-13 05:00 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`pytorch/Makefile` line 9 at r2](https://reviewable.io/reviews/gramineproject/examples/109#-ODwIBzWCjIWzbgKkpHn:-ODyNrqm-8Fd-rKWw8ir:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/78b83e68e8036b8b8c4c5acb3681f9e001687c36/pytorch/Makefile#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need for an empty line here
</blockquote></details>

Done.
___
*[`pytorch/Makefile` line 11 at r2](https://reviewable.io/reviews/gramineproject/examples/109#-ODwIAAXCx4z6ulwLUax:-ODyNs5uEYUzBslZCJbX:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/78b83e68e8036b8b8c4c5acb3681f9e001687c36/pytorch/Makefile#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need for an empty line here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-13 06:03 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-12-16 05:43 UTC, adarshan-intel commented
Can we merge this?

2024-12-22 17:24 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2025-01-06 05:15 UTC, adarshan-intel commented
CI Test please

2025-01-06 05:42 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/109)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-06 05:43 UTC, merged