Replace chroot-based `/tmp/` with tmpfs-based one
gramineproject/examples pull request #37
Opened 2022-07-18 11:49 UTC by dimakuv

This removes the need to add `/tmp/` dir to the list of `sgx.allowed_files`. As a side effect, this commit cleans up `sgx.allowed_files` in GCC and PyTorch examples.

I tested the changes manually.

2022-07-18 11:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/37)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`gcc/gcc.manifest.template` line 25 at r1](https://reviewable.io/reviews/gramineproject/examples/37#-N7G8T7j9ZNSHEOHsG2B:-N7G8T7j9ZNSHEOHsG2C:bw9hck2) ([raw file](https://github.com/gramineproject/examples/blob/87a0803ba3cbb748632d37902d6b71a4f1dfcec2/gcc/gcc.manifest.template#L25)):*
> ```
> ]
> 
> loader.pal_internal_mem_size = "64M"
> ```

FYI: This is because we have `/usr/include/` in `sgx.trusted_files` now
___
*[`pytorch/pytorch.manifest.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/examples/37#-N7G8k0CEo5xl5IS7mWA:-N7G8k0CEo5xl5IS7mWB:be8py1v) ([raw file](https://github.com/gramineproject/examples/blob/87a0803ba3cbb748632d37902d6b71a4f1dfcec2/pytorch/pytorch.manifest.template#L34)):*
> ```
> 
> sgx.nonpie_binary = true
> sgx.enclave_size = "2G"
> ```

FYI: Because we decreased the number of threads, we can significantly reduce the enclave size.
___
*[`pytorch/pytorch.manifest.template` line 35 at r1](https://reviewable.io/reviews/gramineproject/examples/37#-N7G8esH93caqZehOt24:-N7G8esIBz4Z-E3umtDn:b-v2ebnx) ([raw file](https://github.com/gramineproject/examples/blob/87a0803ba3cbb748632d37902d6b71a4f1dfcec2/pytorch/pytorch.manifest.template#L35)):*
> ```
> sgx.nonpie_binary = true
> sgx.enclave_size = "2G"
> sgx.thread_num = 16
> ```

We set `loader.env.OMP_NUM_THREADS = "8"` (see above), so we can limit the number of threads here.
___
*[`pytorch/pytorch.manifest.template` line 52 at r1](https://reviewable.io/reviews/gramineproject/examples/37#-N7G8YSoESyn1qDGH1Fr:-N7G8YSoESyn1qDGH1Fs:b68z8zm) ([raw file](https://github.com/gramineproject/examples/blob/87a0803ba3cbb748632d37902d6b71a4f1dfcec2/pytorch/pytorch.manifest.template#L52)):*
> ```
>   "file:classes.txt",
>   "file:input.jpg",
>   "file:alexnet-pretrained.pt",  # Pre-trained model saved as a file
> ```

FYI: Just for readability, I grouped three inputs together
___
*[`pytorch/pytorch.manifest.template` line 70 at r1](https://reviewable.io/reviews/gramineproject/examples/37#-N7G8b4C3zXzPx0CgnTk:-N7G8b4C3zXzPx0CgnTl:b-rlmljr) ([raw file](https://github.com/gramineproject/examples/blob/af0dc7145f32038a9a295613a6e8bf0548260e52/pytorch/pytorch.manifest.template#L70)):*
> ```
>   "file:/etc/gai.conf",
>   "file:/etc/resolv.conf",
>   "file:/etc/fstab",
> ```

FYI: All this was not needed.


<!-- Sent from Reviewable.io -->

2022-07-18 12:37 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/37)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-07-18 13:36 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/37)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-07-18 14:18 UTC, mkow requested changes
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/37)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`pytorch/pytorchexample.py` line 50 at r2](https://reviewable.io/reviews/gramineproject/examples/37#-N7Gf1Fr9P5EzF6WNI7l:-N7Gf1Fr9P5EzF6WNI7m:undefined) ([raw file](https://github.com/gramineproject/examples/blob/7380e35e81f43eba14040bc7d4ea833c9424bc6d/pytorch/pytorchexample.py#L50)):*
> ```Python
>     outfile.write(str([(classes[idx], percentage[idx].item()) for idx in indices[0][:5]]))
> 
> print("Done. Result is written to `result.txt`.")
> ```





_Suggestion:_
```Python
The result was written
```


<!-- Sent from Reviewable.io -->

2022-07-18 15:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/37)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[`pytorch/pytorchexample.py` line 50 at r2](https://reviewable.io/reviews/gramineproject/examples/37#-N7Gf1Fr9P5EzF6WNI7l:-N7GxZsC2jphiqaHpQWW:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/7380e35e81f43eba14040bc7d4ea833c9424bc6d/pytorch/pytorchexample.py#L50)):*
> ```Python
>     outfile.write(str([(classes[idx], percentage[idx].item()) for idx in indices[0][:5]]))
> 
> print("Done. Result is written to `result.txt`.")
> ```

Done


<!-- Sent from Reviewable.io -->

2022-07-18 15:50 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/37)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-07-18 16:01 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/37)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-07-19 10:25 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/37)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-07-20 14:31 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/37)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-20 14:41 UTC, merged