Increase Pytorch enclave size and thread number
gramineproject/examples pull request #38
Opened 2022-07-23 12:00 UTC by anjalirai-intel

2G enclave size is not sufficient for servers, hence increasing it to 4G

Signed-off-by: Anjali Rai <anjali.rai@intel.com>

2022-07-25 07:00 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/38)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/38#-N7o8qV_E5mGSC8jJWKF):*
What's so special about the servers, that we need to increase to 4G? It looks to be related to the number of threads that you increased (each thread requires some memory, so bumping the number of threads requires bumping the enclave size).
___
*[`pytorch/pytorch.manifest.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/examples/38#-N7o8k3HBf8ERUvg0D2_:-N7o8k3HBf8ERUvg0D2a:b-ig5mx0) ([raw file](https://github.com/gramineproject/examples/blob/6b66b5f35db0f5fba5240f496d310100fa1abdba/pytorch/pytorch.manifest.template#L12)):*
> ```
> # Restrict the maximum number of threads to prevent insufficient memory
> # issue, observed on CentOS/RHEL.
> loader.env.OMP_NUM_THREADS = "8"
> ```

Here you specify that the maximum number of threads is 8. Then why do we need to increase the thread num from 16 to 32?
___
*[`pytorch/pytorch.manifest.template` line 35 at r1](https://reviewable.io/reviews/gramineproject/examples/38#-N7o8hXT5aNKD0Xonkw4:-N7o8hXT5aNKD0Xonkw5:b-eobwcf) ([raw file](https://github.com/gramineproject/examples/blob/6b66b5f35db0f5fba5240f496d310100fa1abdba/pytorch/pytorch.manifest.template#L35)):*
> ```
> sgx.nonpie_binary = true
> sgx.enclave_size = "4G"
> sgx.thread_num = 32
> ```

Why do you need to increase the number of threads?


<!-- Sent from Reviewable.io -->

2022-07-25 10:52 UTC, anjalirai-intel commented
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/38#-N7o8qV_E5mGSC8jJWKF):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's so special about the servers, that we need to increase to 4G? It looks to be related to the number of threads that you increased (each thread requires some memory, so bumping the number of threads requires bumping the enclave size).
</blockquote></details>

These are CentOS & RHEL servers, and when I ran the test it throwed error for increasing threads


<!-- Sent from Reviewable.io -->

2022-07-25 10:54 UTC, anjalirai-intel commented
*[`pytorch/pytorch.manifest.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/examples/38#-N7o8k3HBf8ERUvg0D2_:-N7ozICu95GH3pb7WMG0:bt10336) ([raw file](https://github.com/gramineproject/examples/blob/6b66b5f35db0f5fba5240f496d310100fa1abdba/pytorch/pytorch.manifest.template#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here you specify that the maximum number of threads is 8. Then why do we need to increase the thread num from 16 to 32?
</blockquote></details>

The test worked just by changing the thread_num. I was not sure of this functionality, so I didn't change it


<!-- Sent from Reviewable.io -->

2022-07-25 10:54 UTC, anjalirai-intel commented
*[`pytorch/pytorch.manifest.template` line 35 at r1](https://reviewable.io/reviews/gramineproject/examples/38#-N7o8hXT5aNKD0Xonkw4:-N7ozY2A0xIJzFBniTcw:bw245dm) ([raw file](https://github.com/gramineproject/examples/blob/6b66b5f35db0f5fba5240f496d310100fa1abdba/pytorch/pytorch.manifest.template#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need to increase the number of threads?
</blockquote></details>

When I ran the test on baremetal. test failed with error Not enough threads. So that's why I had to increase it


<!-- Sent from Reviewable.io -->

2022-07-25 12:41 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/38)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/38#-N7o8qV_E5mGSC8jJWKF):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

These are CentOS & RHEL servers, and when I ran the test it throwed error for increasing threads
</blockquote></details>

We'll need to change the commit message to smth like:
```
Increase enclave size and thread number in PyTorch example

For whatever reason, 16 enclave threads is not sufficient on some machines,
so we increase the number of threads to 32. Subsequently, the enclave size
must be bumped to accommodate the increased number of threads.
```
___
*[`pytorch/pytorch.manifest.template` line 35 at r1](https://reviewable.io/reviews/gramineproject/examples/38#-N7o8hXT5aNKD0Xonkw4:-N7pMZWc6qhYpL5-3IY2:bgoe8cj) ([raw file](https://github.com/gramineproject/examples/blob/6b66b5f35db0f5fba5240f496d310100fa1abdba/pytorch/pytorch.manifest.template#L35)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

When I ran the test on baremetal. test failed with error Not enough threads. So that's why I had to increase it
</blockquote></details>

Ok. I don't know why PyTorch needs 4x more threads than the value of `OMP_NUM_THREADS`, but I also don't care (because PyTorch is a pain to understand). I'll just let it pass.


<!-- Sent from Reviewable.io -->

2022-09-07 08:51 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/38)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)



<!-- Sent from Reviewable.io -->

2022-09-07 08:51 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/38)* status: all files reviewed, 1 unresolved discussion (waiting on @anjalirai-intel)



<!-- Sent from Reviewable.io -->

2022-09-07 08:57 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/38)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/38#-N7o8qV_E5mGSC8jJWKF):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We'll need to change the commit message to smth like:
```
Increase enclave size and thread number in PyTorch example

For whatever reason, 16 enclave threads is not sufficient on some machines,
so we increase the number of threads to 32. Subsequently, the enclave size
must be bumped to accommodate the increased number of threads.
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-09-07 09:06 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/38)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-07 09:09 UTC, merged