Increase the number of sgx.max_threads to 8
gramineproject/examples pull request #43
Opened 2022-11-16 05:21 UTC by anjalirai-intel

R on Ubuntu 22.04 requires more threads than specified in OMP_NUM_THREADS because it spawns some additional helper threads.

Signed-off-by: Anjali Rai <anjali.rai@intel.com>

2022-11-16 08:18 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/43)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/43#-NGzVXPkANij_-nDQRqK):*
This should have been:
```
[CI-Examples] Increase `sgx.max_threads` to 8 for R example
```

I'll fix it during final rebase.
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/examples/43#-NGzVhaP7BqHEAnl75ZJ):*
I would say `Newer versions of R (e.g. on Ubuntu 22.04) require ...`
___
*[`r/R.manifest.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/examples/43#-NGzVuk2-L3pUKjS1nNU:-NGzVuk2-L3pUKjS1nNV:b-ss46ex) ([raw file](https://github.com/gramineproject/examples/blob/0c9e7c73ce306bd5c5814e1ef0482342bec6a557/r/R.manifest.template#L34)):*
> ```
> sys.stack.size = "8M"
> sgx.enclave_size = "2G"   # for the R-benchmark-25.R script, specify at least "16G"
> sgx.max_threads = 8
> ```

BTW, I thought that I changed all `sgx.thread_num` -> `sgx.max_threads`. Interesting...


<!-- Sent from Reviewable.io -->

2022-11-16 08:20 UTC, dimakuv commented
Jenkins, test this please

2022-11-16 08:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/43)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

___
*[`r/R.manifest.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/examples/43#-NGzVuk2-L3pUKjS1nNU:-NGzWgxA-jlKb79tr1gl:b-8amdxl) ([raw file](https://github.com/gramineproject/examples/blob/0c9e7c73ce306bd5c5814e1ef0482342bec6a557/r/R.manifest.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, I thought that I changed all `sgx.thread_num` -> `sgx.max_threads`. Interesting...
</blockquote></details>

Ah, this is in examples repo. I already have a PR and waiting for new Gramine release to merge it: https://github.com/gramineproject/examples/pull/41


<!-- Sent from Reviewable.io -->

2022-11-16 09:44 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/43)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/43#-NGzVXPkANij_-nDQRqK):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should have been:
```
[CI-Examples] Increase `sgx.max_threads` to 8 for R example
```

I'll fix it during final rebase.
</blockquote></details>

Actually, should be `sgx.thread_num`, see other comments.
___
*[`r/R.manifest.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/examples/43#-NGzVuk2-L3pUKjS1nNU:-NGzoapG41Lotvf2BUAI:b-9v5hmh) ([raw file](https://github.com/gramineproject/examples/blob/0c9e7c73ce306bd5c5814e1ef0482342bec6a557/r/R.manifest.template#L34)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Are you planning to merge your PR before release
</blockquote></details>

No, that PR should be merged *after* release.

Which made me realize -- please fix it back to `sgx.thread_num`.


<!-- Sent from Reviewable.io -->

2022-11-16 10:12 UTC, anjalirai-intel commented
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/43#-NGzVXPkANij_-nDQRqK):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, should be `sgx.thread_num`, see other comments.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 10:12 UTC, anjalirai-intel commented
*[`r/R.manifest.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/examples/43#-NGzVuk2-L3pUKjS1nNU:-NGzvDaB3IBCSOKcOowD:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/0c9e7c73ce306bd5c5814e1ef0482342bec6a557/r/R.manifest.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, that PR should be merged *after* release.

Which made me realize -- please fix it back to `sgx.thread_num`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 12:08 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/43)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/examples/43#-NH-KcwECm-SsBwBBWiD):*
`R(` -> `R (`
___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/examples/43#-NH-KgHn0FTUINDrmkE4):*
`requires` -> `require`
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/examples/43#-NH-KjcEDNP0Ov2Xga6m):*
`it spawns` -> `they spawn`


<!-- Sent from Reviewable.io -->

2022-11-16 15:23 UTC, anjalirai-intel commented
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/gramineproject/examples/43#-NH-KgHn0FTUINDrmkE4):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`requires` -> `require`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 16:02 UTC, anjalirai-intel commented
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/examples/43#-NH-KjcEDNP0Ov2Xga6m):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done (`spawn`, not `spawns`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 18:58 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/43)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-11-22 14:32 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/43)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-22 14:33 UTC, merged