Add distro and torchvision version used to test PyTorch example
gramineproject/examples pull request #55
Opened 2023-02-28 11:59 UTC by jkr0103

Commit [2e41bcd](https://github.com/gramineproject/examples/commit/2e41bcd1d1887a364fced4bd220e654c9ae41ff0) breaks pytorch example on `ubuntu 18.04`. Changes in above commit works with `torchvision version 0.13.0` or above which is available with `python 3.7` and above but `ubuntu 18.04` comes with `python3.6.9`, hence we cannot install torchvision version 0.13.0 and example breaks.

More info about torchvision versions compatibility with python version https://pypi.org/project/torchvision/

Changes in this PR inform user about the torchvison version and dostro used for testing this example. We don't necessarility have to make it work with `ubuntu 18.04` as it's reaching EOF in 1 month.

2023-02-28 13:19 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/55)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/examples/55#-NPNAINC9EMtU7JVCrV2):*
Please add the commit body message -- just copy-paste the text from your PR description ("Commit ... broke ...")


<!-- Sent from Reviewable.io -->

2023-02-28 15:35 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/55)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2023-02-28 16:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/55)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/55#-NPNkPSh4k4-gw5rApjo:-NPNkPSh4k4-gw5rApjp:b-az9sjc) (no related file):*
Based on discussions in https://github.com/gramineproject/examples/issues/53, this note in the README may be not enough (we may want to keep the old code for older PyTorch versions). Let me block until we decide.

___


<!-- Sent from Reviewable.io -->

2023-02-28 16:11 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/55)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/55#-NPNkPSh4k4-gw5rApjo:-NPNmYHL3pNKmersYNS4:b-o3ip1a) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Based on discussions in https://github.com/gramineproject/examples/issues/53, this note in the README may be not enough (we may want to keep the old code for older PyTorch versions). Let me block until we decide.
</blockquote></details>

IMO it's enough, we don't support 18.04 anymore.

___


<!-- Sent from Reviewable.io -->

2023-03-01 04:53 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/55)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/55#-NPNkPSh4k4-gw5rApjo:-NPQVS5g34KxgGpgRTHY:bc2ukhd) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMO it's enough, we don't support 18.04 anymore.
</blockquote></details>

Can we add more text to README saying `minimum required torchvision version is 0.13.0. If your system supports lower than 0.13.0, please use example repo v.1.4 tag?

___


<!-- Sent from Reviewable.io -->

2023-03-01 09:40 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/55)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/55#-NPRXjdXC37D068n27PO:-NPRXjdXC37D068n27PP:bmls3tz) (no related file):*
Blocking this PR. I think my PR is better: https://github.com/gramineproject/examples/pull/56

___


<!-- Sent from Reviewable.io -->

2023-03-07 09:52 UTC, closed without merging