[Examples] Add OpenVINO benchmarking examples
gramineproject/examples pull request #6
Opened 2021-09-22 14:10 UTC by sahason

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Examples to run "Benchmark C++ Tool" (benchmark_app) from the OpenVINO distribution under Graphene-SGX to estimate deep learning inference performance.

## How to test this PR? 
Please follow the steps present in `openvino/README.md`

2021-12-01 06:35 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: 2 of 5 files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj4X3MDH7M4Vdx4zfw:-Mpk9Xlc5FnABh-aHrqm:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

After a rebase, please replace all `Graphene` with `Gramine`.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj31LEBjnVJjw_ZauR:-MpogHUu89egvcnwQtxh:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rebase this example to the latest master. Also please make sure it still builds and runs correctly with the latest (v1.0) release of Gramine.
</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj2jkT5HdKLV7uG6ZE):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for `[Examples]` prefix -- we are already in the Examples repo.
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 7 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj39fOEuk1yOVUaR9L:-MpkAnut2HjSvJQcZIe8:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/benchmark_app.manifest.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have `{{ arch_libdir }}` and `/usr/{{ arch_libdir }}` separated by several OpenVINO paths? I mean, this looks weird; is there a particular reason?

If there is no reason for this, then I would prefer to have both these directories at the very end (just like in all other examples).
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 9 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj2y2u0VkE7kTXLRxk:-MpkB_IO39Au7g3aHJhF:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/benchmark_app.manifest.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you move this line to other lines with `true/false` options? Just for readability.
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 35 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj3TSX0qQg7dusYBhE:-MpkBaB99PsYNdxL7LuU:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/benchmark_app.manifest.template#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this really needed? Pretty sure this line can be removed.
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 47 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj3c-QAaiYkZQOYjk2:-MpkCMTA8wojnTp6ZHBt:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/benchmark_app.manifest.template#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you move this line after all `openvino_dir` entries? Otherwise it looks weird: you have `openvino_dir` entries above and `openvino_dir` entries below.
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 47 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj3uhE2PvEDWaMu2_x:-MpkCS262AE0iCGlALox:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/benchmark_app.manifest.template#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not simply `"file:{{ inference_engine_cpp_samples_build }}/intel64/Release/lib"`? This way you'll cover all libraries under this path, which is less future-prone.
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 49 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj3mgWB43l-T2SaS16:-MpkCWgn5CSz-aeRZP1b:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/benchmark_app.manifest.template#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not simply `"file:{{ openvino_dir }}/deployment_tools/ngraph/lib"`? This way you'll cover all libraries under this path, which is less future-prone.
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 59 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj3zg139QtWQaJsdMW:-MpkClEd51ad1zuXSRYc:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/benchmark_app.manifest.template#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort these filenames.
</blockquote></details>

Done.
___
*[openvino/Makefile, line 1 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj43vV238UpncsASci:-MpkCz-L42NrlEeaOZkK:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/Makefile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`#Use` -> `# use`
</blockquote></details>

Done.
___
*[openvino/Makefile, line 9 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj47jd4Zp-ZmmGdhDF:-MpkD96K9H__S7eIhQ_i:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/Makefile#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have double-space here
</blockquote></details>

Done.
___
*[openvino/Makefile, line 79 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj7im8BScG2ls3HX5Y:-MpkN0p83CHoSSP0RYxp:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/Makefile#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add another tab to make it explicit these are continuation lines of the `graphene-manifest` command
</blockquote></details>

Done.
___
*[openvino/Makefile, line 87 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj7oeq1HK-f63ojupa:-MpkNFqy6yJ0DKLRnUjT:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/Makefile#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add another tab to make it explicit these are continuation lines of the `graphene-sgx-sign` command.

Also, we don't allow `-argument` anymore. It always has to be `--` (double dash), as is classic in Linux.
</blockquote></details>

Done.
___
*[openvino/Makefile, line 96 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj88Mv5yU2TB01Guew:-MpkNj8h3jg34bMQVOj2:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/fa28a74f973fe3ad20c9806cd0d6ba5308c065b7/openvino/Makefile#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you split it into three lines? Hard to read
</blockquote></details>

Done.
___
*[openvino/README.md, line 8 at r1](https://reviewable.io/reviews/gramineproject/examples/6#-Mlj6b [...]

2021-12-01 08:35 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp6kdNEo5tuEhy0KaV:-Mpp6kdNEo5tuEhy0KaW:b-12lau1) (no related file):*
You should add more "git ignore" files/dirs to `.gitignore`. In particular, you should add at least these:
- `/inference_engine_cpp_samples_build`
-  `/benchmark_app`
- `/output`

Basically, you need to add all files/dirs that are created during OpenVINO build/run.

---
___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp6H2hCVsceQ6gORvv):*
`examples` -> `example`
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp5OAu8dQCvYYRsM55):*
We'll need to add a commit body message like this:
```
This commit replaces the old OpenVINO `object_detection_sample_ssd` example.
Now the OpenVINO example may be used for benchmarking purposes.
```

We'll do it during final rebase.
___
*[openvino/benchmark_app.manifest.template, line 1 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp68-N8IsLVta2Nu3k:-Mpp68-O9V-t6PPMVzO7:b-a3spty) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/benchmark_app.manifest.template#L1)):*
> ```
> # OpenVINO (benchmark_app) manifest example
> ```

Could you remove this comment (and the following empty line)? At some point we decided to remove such useless comments (the user is already in this directory, so the user knows what this manifest file is about).
___
*[openvino/benchmark_app.manifest.template, line 34 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp5jEi1kKTA1tf4KvT:-Mpp5jEi1kKTA1tf4KvU:b-r26up8) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/benchmark_app.manifest.template#L34)):*
> ```
> 
> sgx.enclave_size = "32G"
> sgx.thread_num = 196
> ```

Could you add an empty line after this, so there is a clear distinction between SGX-numbers options and `true/false` options.
___
*[openvino/benchmark_app.manifest.template, line 49 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp0Yym2opd37wuJFDA:-Mpp0Yym2opd37wuJFDB:bknhgem) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/benchmark_app.manifest.template#L49)):*
> ```
>   "file:{{ inference_engine_cpp_samples_build }}/intel64/Release/lib/",
>   "file:benchmark_app",
>   "file:./model/"
> ```

Could you replace `./model/` with simply `model/`

Also, please keep the comma at the end of the line (like it was before) -- this is allowed in TOML files, and it will be easier to add more lines to this list in the future.
___
*[openvino/benchmark_app.manifest.template, line 58 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp0pQ82j5GrbKskp02:-Mpp0pQ82j5GrbKskp03:bopqq2c) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/benchmark_app.manifest.template#L58)):*
> ```
>   "file:/etc/nsswitch.conf",
>   "file:/etc/passwd",
>   "file:output.txt"
> ```

please keep the comma at the end of the line (like it was before) -- this is allowed in TOML files, and it will be easier to add more lines to this list in the future.
___
*[openvino/README.md, line 27 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp7EW000ZiXD0YZk9E:-Mpp7EW000ZiXD0YZk9F:b-hofzt7) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L27)):*
> ```Markdown
> - bert-large-uncased-whole-word-masking-squad-int8-0001 (INT8)
> - brain-tumor-segmentation-0001 (FP16/FP32)
> - brain-tumor-segmentation-0002 (FP16/FP32)
> ```

There seems to be no logic in the ordering of these models. Can we sort them alphabetically?
___
*[openvino/README.md, line 89 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp2_8A4lKaFnrNKFah:-Mpp2_8B6GsYDDt4siAN:bhtebkj) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L89)):*
> ```Markdown
> - To get `number of physical cores`, do `lscpu | grep 'Core(s) per socket'`.
> - Option `i <image files>` is optional. A user may use this option as required.
> - Please tune batch size to get best performance in your system.
> ```

`the batch size`, `the best performance`

`in your system` -> `on your system`
___
*[openvino/README.md, line 93 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp2n0uB4ATOCV39_hC:-Mpp2n0uB4ATOCV39_hD:bcd5awr) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L93)):*
> ```Markdown
> the models these are stored in `model/public` directory.
> - Based on the precision for bert-large and brain-tumor-segmentation models the enclave
> size must be set to 64/128 GB for capturing throughput.
> ```

I don't understand this note. What does it mean "based on precision"? Could you expand on this -- what kinds of precision need bigger enclave sizes? And why is it only about throughput, what about latency?
___
*[openvino/README.md, line 96 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp302fCKf8VPgHmnTp:-Mpp302fCKf8VPgHmnTq:b-8kvkh8) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L96)):*
> ```Markdown
> - In multi-socket systems for bert-large-uncased-whole-word-masking-squad-0001 and
> brain-tumor-segmentation-0001 FP32/FP16 models please expand memory nodes usage with
> `numactl --membind` if memory allocation fails for capturing throughput.
> ```

What does it mean "expand memory nodes usage"? Do you mean that the user must `membind` to more than one NUMA node? Please expand.
___
*[openvino/README.md, line 100 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp3OyS8BwdgM-NC-bZ:-Mpp3OyS8BwdgM-NC-b_:b-sf3p2k) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L100)):*
> ```Markdown
> ## Performance considerations
> 
> ### Scale the CPU frequency
> ```

Let's rename to `CPU frequency scaling`
___
*[openvino/README.md, line 115 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp3X2O0_G_lfAy6Fnp:-Mpp3X2O0_G_lfAy6Fnq:b-h6wkdt) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L115)):*
> ```Markdown
> 
> - Preheat manifest option pre-faults the enclave memory and moves the performance penalty to
> gramine-sgx startup (before the workload starts executing). To use preheat option, add
> ```

`use preheat option` -> `use the preheat option`
___
*[openvino/README.md, line 116 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp3gPV27RItzCQ9moh:-Mpp3gPV27RItzCQ9moi:b-7fkc12) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L116)):*
> ```Markdown
> - Preheat manifest option pre-faults the enclave memory and moves the performance penalty to
> gramine-sgx startup (before the workload starts executing). To use preheat option, add
> `sgx.preheat_enclave = true` to the manifest template.
> ```

You already have this option in the manifest template. Maybe rephrase to
```
To use the preheat option, make sure that `sgx.preheat_enclave = true` is added to 
the manifest template.
```
___
*[openvino/README.md, line 120 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp3sxi9L0BZ7cTZfjp:-Mpp3sxi9L0BZ7cTZfjq:b-y8h0p9 [...]

2021-12-01 12:42 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: 3 of 6 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp6kdNEo5tuEhy0KaV:-MppTlDXEeGNrLeBBZCn:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should add more "git ignore" files/dirs to `.gitignore`. In particular, you should add at least these:
- `/inference_engine_cpp_samples_build`
-  `/benchmark_app`
- `/output`

Basically, you need to add all files/dirs that are created during OpenVINO build/run.
</blockquote></details>

Done.

---
___
*[-- commits, line 3 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp6H2hCVsceQ6gORvv):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`examples` -> `example`
</blockquote></details>

Done.
___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp5OAu8dQCvYYRsM55):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We'll need to add a commit body message like this:
```
This commit replaces the old OpenVINO `object_detection_sample_ssd` example.
Now the OpenVINO example may be used for benchmarking purposes.
```

We'll do it during final rebase.
</blockquote></details>

OK.
___
*[openvino/benchmark_app.manifest.template, line 1 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp68-N8IsLVta2Nu3k:-MppU49C2-Y0w5jv3V20:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/benchmark_app.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you remove this comment (and the following empty line)? At some point we decided to remove such useless comments (the user is already in this directory, so the user knows what this manifest file is about).
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 34 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp5jEi1kKTA1tf4KvT:-MppUARc9vbQoApKmXH-:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/benchmark_app.manifest.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add an empty line after this, so there is a clear distinction between SGX-numbers options and `true/false` options.
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 49 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp0Yym2opd37wuJFDA:-MppUEtO3CQtZqM2obpI:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/benchmark_app.manifest.template#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you replace `./model/` with simply `model/`

Also, please keep the comma at the end of the line (like it was before) -- this is allowed in TOML files, and it will be easier to add more lines to this list in the future.
</blockquote></details>

Done.
___
*[openvino/benchmark_app.manifest.template, line 58 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp0pQ82j5GrbKskp02:-MppULIq9Fl44YglGhcC:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/benchmark_app.manifest.template#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

please keep the comma at the end of the line (like it was before) -- this is allowed in TOML files, and it will be easier to add more lines to this list in the future.
</blockquote></details>

Done.
___
*[openvino/README.md, line 27 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp7EW000ZiXD0YZk9E:-MppUo-u9sp2XiW2simO:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There seems to be no logic in the ordering of these models. Can we sort them alphabetically?
</blockquote></details>

Done.
___
*[openvino/README.md, line 89 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp2_8A4lKaFnrNKFah:-MppWG-R5t45NkfLxtFa:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the batch size`, `the best performance`

`in your system` -> `on your system`
</blockquote></details>

Done.
___
*[openvino/README.md, line 93 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp2n0uB4ATOCV39_hC:-MppWS2s90ab68v2pCjM:b-k8112e) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand this note. What does it mean "based on precision"? Could you expand on this -- what kinds of precision need bigger enclave sizes? And why is it only about throughput, what about latency?
</blockquote></details>

I will remove precision. It mostly depends on the model size of different models. For bert-large it requires 64 GB and for brain-tumor-segmentation-0001 and 0002 it requires 128 GB memory. 

No for latency it does not change based on the model.  Options `-nireq`, `-nstreams` and `-nthreads` are set as `number of physical cores * 2` for throughput capturing whereas these options are set as 1 by default for latency capturing hence for latency 32 GB enclave size is enough for all the models.
___
*[openvino/README.md, line 96 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp302fCKf8VPgHmnTp:-MppbaW42-KC8VaHspPI:bb77ufg) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does it mean "expand memory nodes usage"? Do you mean that the user must `membind` to more than one NUMA node? Please expand.
</blockquote></details>

Yes.
___
*[openvino/README.md, line 100 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp3OyS8BwdgM-NC-bZ:-MppcW-G6dY_OLGl1B_S:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's rename to `CPU frequency scaling`
</blockquote></details>

Done.
___
*[openvino/README.md, line 115 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp3X2O0_G_lfAy6Fnp:-Mppczky537ahFxwqVfe:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`use preheat option` -> `use the preheat option`
</blockquote></details>

Done.
___
*[openvino/README.md, line 116 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp3gPV27RItzCQ9moh:-MppczOt5JVwlmkGuBZl:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You already have this option in the man [...]

2021-12-03 08:35 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @sahason)

___
*[openvino/.gitignore, line 9 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzMlkr3pZm2RLlegCQ:-MpzMlkr3pZm2RLlegCR:bli0kx9) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/.gitignore#L9)):*
> ```ignore
> *.manifest.sgx
> *.sig
> *.token
> ```

Please remove the last four items. These patterns are already covered by a top-level `.gitignore` file: https://github.com/gramineproject/examples/blob/master/.gitignore#L2-L5

(Recall that `.gitignore` files accumulate through directories. So the top-level file contents are appended to the contents of your file.)
___
*[openvino/README.md, line 93 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp2n0uB4ATOCV39_hC:-MpzNTUW7tH2CYmOU_Vu:b-wsvasg) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L93)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I will remove precision. It mostly depends on the model size of different models. For bert-large it requires 64 GB and for brain-tumor-segmentation-0001 and 0002 it requires 128 GB memory. 

No for latency it does not change based on the model.  Options `-nireq`, `-nstreams` and `-nthreads` are set as `number of physical cores * 2` for throughput capturing whereas these options are set as 1 by default for latency capturing hence for latency 32 GB enclave size is enough for all the models.


</blockquote></details>

Thanks for the explanation!
___
*[openvino/README.md, line 96 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp302fCKf8VPgHmnTp:-MpzNbuR-vTQHJfZ8_uG:bdzca82) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L96)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Ok, what about this re-phrasing then:
```
... brain-tumor-segmentation-0001 FP32/FP16 models, add more NUMA nodes using
`numactl --membind` if memory allocation fails (for throughput runs).
```

(Please also re-wrap my suggested text to 80 chars)
___
*[openvino/README.md, line 62 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzOTU_7Nz5uw91ePxF:-MpzOTU_7Nz5uw91ePxG:bs3cvds) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L62)):*
> ```Markdown
> #### Native
> 
> To run the benchmark in a native baremetal (outside Gramine), replace `gramine-sgx benchmark_app`
> ```

`in a native baremetal` -> `natively`
___
*[openvino/README.md, line 78 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzOWp-CfiYxXf31eb6:-MpzOWp-CfiYxXf31eb7:bs3cvds) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L78)):*
> ```Markdown
> #### Native
> 
> To run the benchmark in a native baremetal (outside Gramine), replace `gramine-sgx benchmark_app`
> ```

`in a native baremetal` -> `natively`
___
*[openvino/README.md, line 85 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzPFTI0QGu5kTg13RJ:-MpzPFTI0QGu5kTg13RK:b-b86w1) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L85)):*
> ```Markdown
> - The models require ~3GB of disk space.
> - After setting up OpenVINO environment variables if you want to build Gramine after
> cleaning you need to unset `LD_LIBRARY_PATH`. Please make sure to set up OpenVINO environment
> ```

`to build Gramine after cleaning` -> `to re-build Gramine`
___
*[openvino/README.md, line 88 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzPNxJEnYU73bDdCtR:-MpzPNxJEnYU73bDdCtS:buh0r7i) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L88)):*
> ```Markdown
> variables after building Gramine again.
> - To get `number of physical cores`, do `lscpu | grep 'Core(s) per socket'`.
> - Option `i <image files>` is optional. A user may use this option as required.
> ```

`i` -> `-i` (you forgot the minus sign)
___
*[openvino/README.md, line 88 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzQ-PfBNNsGfm6g23F:-MpzQ-PfBNNsGfm6g23G:bg63u3o) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L88)):*
> ```Markdown
> variables after building Gramine again.
> - To get `number of physical cores`, do `lscpu | grep 'Core(s) per socket'`.
> - Option `i <image files>` is optional. A user may use this option as required.
> ```

`A user may use this option as required.` -- this phrase is obvious. Either delete this sentence, or make it explicit (like, the user may use this option to benchmark specific images rather than randomly generated ones.)
___
*[openvino/README.md, line 91 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzQI9C2fd-wIajxJ4e:-MpzQI9C2fd-wIajxJ4f:b-qyj50l) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L91)):*
> ```Markdown
> - Please tune the batch size to get the best performance on your system.
> - Model files for bert-large can be found in `model/intel` directory and for rest of
> the models these are stored in `model/public` directory.
> ```

This sentence sounds weird. Make it more uniform:
```
- Models for bert-large can be found in `model/intel` directory; the rest of
the models can be found in `model/public` directory.
```
___
*[openvino/README.md, line 93 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzOD6o36_NhXeQ8R7R:-MpzOD6o36_NhXeQ8R7S:b-r1i9we) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L93)):*
> ```Markdown
> the models these are stored in `model/public` directory.
> - For bert-large and brain-tumor-segmentation models the enclave
> size must be set to 64/128 GB for capturing throughput.
> ```

I dislike this `for capturing throughput`. Please replace with `for throughput runs`
___
*[openvino/README.md, line 115 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzOZjK2xKzyqnYlGYe:-MpzOZjK2xKzyqnYlGYf:b-bjuzd6) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L115)):*
> ```Markdown
> 
> - Preheat manifest option pre-faults the enclave memory and moves the performance penalty to
> gramine-sgx startup (before the workload starts executing). To use the preheat option, make sure
> ```

`gramine-sgx` -> `Gramine-SGX`
___
*[openvino/README.md, line 124 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzPjLf70WjnAnY-TGC:-MpzPjLf70WjnAnY-TGD:bj4b0x) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L124)):*
> ```Markdown
> 
> TCMalloc and mimalloc are memory allocator libraries from Google and Microsoft that can help
> improve performance significantly based on the workloads. At any point, only one of these
> ```

Just remove `At any point,`; it doesn't add any value to the sentence.
___
*[openvino/README.md, line 131 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzQbTGDGCGjDp-Bo4w:-MpzQbTGDGCGjDp-Bo4x:bw6lvt6) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/README.md#L131)):*
> ```Markdown
> (Please update the binary location and name if different from default. [...]

2021-12-06 05:47 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: 4 of 6 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[openvino/.gitignore, line 9 at r3](https://reviewable.io/reviews/gramineproject/examples/6#-MpzMlkr3pZm2RLlegCQ:-MqD3ei-BkwL8lay2X4A:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/71b5178559f2d53720a2a618dcfc74eed56b108c/openvino/.gitignore#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the last four items. These patterns are already covered by a top-level `.gitignore` file: https://github.com/gramineproject/examples/blob/master/.gitignore#L2-L5

(Recall that `.gitignore` files accumulate through directories. So the top-level file contents are appended to the contents of your file.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-06 08:55 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[openvino/README.md, line 75 at r4](https://reviewable.io/reviews/gramineproject/examples/6#-MqDwJ4y0XWlfnDcl9UT:-MqDwJ4y0XWlfnDcl9UU:bbyjoqa) ([raw file](https://github.com/gramineproject/examples/blob/3e69824924b89e5d449cc3152fa14fc671e24a7e/openvino/README.md#L75)):*
> ```Markdown
> 
> - The models require ~3GB of disk space.
> - After setting up OpenVINO environment variables if you want to re-build gramine you need to unset `LD_LIBRARY_PATH`. Please make sure to set up OpenVINO environment
> ```

`gramine` -> `Gramine`.

Also, please re-wrap to 80 chars per line.
___
*[openvino/README.md, line 78 at r4](https://reviewable.io/reviews/gramineproject/examples/6#-MqDwUUV2qjWvUXFVerQ:-MqDwUUV2qjWvUXFVerR:bfn5dno) ([raw file](https://github.com/gramineproject/examples/blob/3e69824924b89e5d449cc3152fa14fc671e24a7e/openvino/README.md#L78)):*
> ```Markdown
> variables after building Gramine again.
> - To get `number of physical cores`, do `lscpu | grep 'Core(s) per socket'`.
> - Option `-i <image files>` is optional. The user may use this option to benchmark specific images rather than randomly generated ones.
> ```

please re-wrap to 80 chars per line.


<!-- Sent from Reviewable.io -->

2021-12-07 05:05 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[openvino/README.md, line 96 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp302fCKf8VPgHmnTp:-MqD5a1q-lSBk_79YbsW:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/3c3762ccaf61f44e52ac529ae6d55ad7fa3852a6/openvino/README.md#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, what about this re-phrasing then:
```
... brain-tumor-segmentation-0001 FP32/FP16 models, add more NUMA nodes using
`numactl --membind` if memory allocation fails (for throughput runs).
```

(Please also re-wrap my suggested text to 80 chars)
</blockquote></details>

Done
___
*[openvino/README.md, line 75 at r4](https://reviewable.io/reviews/gramineproject/examples/6#-MqDwJ4y0XWlfnDcl9UT:-MqIG4SBEDS7kkxFLD53:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3e69824924b89e5d449cc3152fa14fc671e24a7e/openvino/README.md#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`gramine` -> `Gramine`.

Also, please re-wrap to 80 chars per line.
</blockquote></details>

Done.
___
*[openvino/README.md, line 78 at r4](https://reviewable.io/reviews/gramineproject/examples/6#-MqDwUUV2qjWvUXFVerQ:-MqIG1i4AgQxakDA9Kis:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/3e69824924b89e5d449cc3152fa14fc671e24a7e/openvino/README.md#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

please re-wrap to 80 chars per line.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-12-09 13:27 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-01-20 14:38 UTC, mkow requested changes
> Reviewed 2 of 5 files at r1, 1 of 3 files at r2, 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[openvino/Makefile, line 63 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtrtztn5bOs5-SK11dG:-Mtrtztn5bOs5-SK11dH:b-mvh92z) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/Makefile#L63)):*
> ```Makefile
> 	&& deactivate
> 
> $(VENV_DIR):
> ```

Directory dependencies have some weird semantics in Make, better to use an artificial `$(VENV_DIR)/.INSTALLATION_OK` or something like this (but you'll have to declare it as `PRECIOUS` or `INTERMEDIATE`, I don't remember which one was correct, you need to read Make docs).
Also, the current version will end up in a corrupted state if any of the commands after `mkdir` fail - next builds will incorrectly succeed.
___
*[openvino/README.md, line 20 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcd79L0sxdDDMcmuNo:-Mtcd79M87FgYkoFjtnT:bh5ink0) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L20)):*
> ```Markdown
> ## Supported models for Gramine-SGX
> 
> The following models have been enabled and tested with Gramine-SGX:
> ```

`enabled and tested` -> `tested` (not sure what "enabled" means in this context)
___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcg58gB6GMxhBwTIL-:-Mtcg58gB6GMxhBwTIL0:brx1ret) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
> ```Markdown
> 
> Options `-nireq`, `-nstreams` and `-nthreads` should be set to the
> `number of physical cores * 2` (take into account hyperthreading) for achieving maximum
> ```

`take into account hyperthreading` -> `to take hyperthreading into account`
___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-MtcgEn532UQRCM1QBB6:-MtcgEn532UQRCM1QBB7:bdr24by) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
> ```Markdown
> 
> Options `-nireq`, `-nstreams` and `-nthreads` should be set to the
> `number of physical cores * 2` (take into account hyperthreading) for achieving maximum
> ```

Why not just asking the user to use the number of logical/hyper threads here? HT may be disabled on the server b/c of side channel vulnerabilities and they should know what hyper-threading is.
___
*[openvino/README.md, line 46 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcfv_l4aCZoQ_FJm4j:-Mtcfv_l4aCZoQ_FJm4k:bhh4liv) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L46)):*
> ```Markdown
> 
> ```bash
> $ export OPTIMAL_VALUE=<number of physical cores * 2>
> ```

`OPTIMAL_VALUE` -> `THREADS_CNT`
___
*[openvino/README.md, line 116 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtrt7n-7yBLvCi3Yxgh:-Mtrt7n-7yBLvCi3Yxgi:b-q58ajl) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L116)):*
> ```Markdown
> 
> TCMalloc and mimalloc are memory allocator libraries from Google and Microsoft that can help
> improve performance significantly based on the workloads. Only one of these
> ```

`can be used` -> `can be used at the same time`


<!-- Sent from Reviewable.io -->

2022-02-11 11:51 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: 4 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[openvino/Makefile, line 63 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtrtztn5bOs5-SK11dG:-MvcA71f0csqdrLzRytv:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/Makefile#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Directory dependencies have some weird semantics in Make, better to use an artificial `$(VENV_DIR)/.INSTALLATION_OK` or something like this (but you'll have to declare it as `PRECIOUS` or `INTERMEDIATE`, I don't remember which one was correct, you need to read Make docs).
Also, the current version will end up in a corrupted state if any of the commands after `mkdir` fail - next builds will incorrectly succeed.
</blockquote></details>

Done.
___
*[openvino/README.md, line 20 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcd79L0sxdDDMcmuNo:-Mvak_PODAcBvIla-TTy:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`enabled and tested` -> `tested` (not sure what "enabled" means in this context)
</blockquote></details>

Done.
___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcg58gB6GMxhBwTIL-:-MvakreTE_1H9O1Qzx1I:b-4ma3im) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`take into account hyperthreading` -> `to take hyperthreading into account`
</blockquote></details>

replaced with number of logical cores.
___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-MtcgEn532UQRCM1QBB6:-MvbSbes1RWBlFy7bkBH:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just asking the user to use the number of logical/hyper threads here? HT may be disabled on the server b/c of side channel vulnerabilities and they should know what hyper-threading is.
</blockquote></details>

Done.
___
*[openvino/README.md, line 46 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcfv_l4aCZoQ_FJm4j:-MvbSd2J7YRVMa_oS04w:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`OPTIMAL_VALUE` -> `THREADS_CNT`
</blockquote></details>

Done.
___
*[openvino/README.md, line 116 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtrt7n-7yBLvCi3Yxgh:-MvalbaP6COnkMSnnRNN:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L116)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`can be used` -> `can be used at the same time`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-11 13:46 UTC, mkow requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcg58gB6GMxhBwTIL-:-Mvd0nX1DZEh03vAFOZr:b-bz53to) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

replaced with number of logical cores.
</blockquote></details>

I think the correct term is "logical cores", not "logical threads"?
___
*[openvino/README.md, line 46 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcfv_l4aCZoQ_FJm4j:-Mvd0gvvDqbm8_iYyU4F:b55ctwq) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L46)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please use "logical cores" as above, this calculation isn't always correct (as I said above, you can have HT disabled).
___
*[openvino/README.md, line 78 at r6](https://reviewable.io/reviews/gramineproject/examples/6#-Mvd1D-R00Aozs4kTf2S:-Mvd1D-R00Aozs4kTf2T:b-tdbg5g) ([raw file](https://github.com/gramineproject/examples/blob/ac3ca93329cc29d7ff62799617b3eab8b435cef7/openvino/README.md#L78)):*
> ```Markdown
> OpenVINO environment variables after building Gramine again.
> - To get `Core(s) per socket`, do `lscpu | grep 'Core(s) per socket'`.
> - To get `Thread(s) per core`, do `lscpu | grep 'Thread(s) per core'`.
> ```

This will also need an update after you fix my remarks above.


<!-- Sent from Reviewable.io -->

2022-02-14 05:21 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: 5 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcg58gB6GMxhBwTIL-:-MvqaGRY-NCUy3Z0dpA-:b-j5way9) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think the correct term is "logical cores", not "logical threads"?
</blockquote></details>

Here the optimal value for best performance is found as the number of logical cores in one socket not the total number of logical cores in a multi-socket system. So I have changed this as logical cores per socket.
___
*[openvino/README.md, line 46 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcfv_l4aCZoQ_FJm4j:-Mvq_6ju6_kYJkOyBzoK:bpn3h3v) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use "logical cores" as above, this calculation isn't always correct (as I said above, you can have HT disabled).
</blockquote></details>

Here the optimal value for best performance is found as the number of logical cores in one socket. Even if HT disabled Thread(s) per core will be 1. So this calculation seems fine.
___
*[openvino/README.md, line 78 at r6](https://reviewable.io/reviews/gramineproject/examples/6#-Mvd1D-R00Aozs4kTf2S:-Mvqa4nq3Lh2ZPDVcDJ0:b-gmvyld) ([raw file](https://github.com/gramineproject/examples/blob/ac3ca93329cc29d7ff62799617b3eab8b435cef7/openvino/README.md#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This will also need an update after you fix my remarks above.
</blockquote></details>

Here the optimal value for best performance is found as the number of logical cores in one socket. Even if HT is disabled Thread(s) per core will be 1. So this calculation seems fine.


<!-- Sent from Reviewable.io -->

2022-02-14 14:30 UTC, mkow requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @sahason)

___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcg58gB6GMxhBwTIL-:-MvsciopCC565133EIDb:b-ghvcju) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Here the optimal value for best performance is found as the number of logical cores in one socket not the total number of logical cores in a multi-socket system. So I have changed this as logical cores per socket.
</blockquote></details>

Hmm, does this mean that not using the other CPU at all is faster than using it?


<!-- Sent from Reviewable.io -->

2022-02-15 08:03 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcg58gB6GMxhBwTIL-:-MvwJAxV49vTryhrsuMh:b-i93x1t) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, does this mean that not using the other CPU at all is faster than using it?
</blockquote></details>

Please note the usage of `numactl --cpubind=0 --membind=0` in this command. So this is executing the command only on node 0. On a 36 cores system, the number of logical cores available to run this command will be 36 if hyperthreading is disabled and 72 if hyperthreading is enabled. The best performance can be achieved if we run 36 threads if hyperthreading is disabled and 72 threads if hyperthreading is enabled. Hence the THREAD_CNT is calculated as `Core(s) per socket * Thread(s) per core`. As per the command it is using all the allocated CPUs.


<!-- Sent from Reviewable.io -->

2022-02-15 14:52 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @sahason)

___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcg58gB6GMxhBwTIL-:-MvxqrYr2FNlT64rGHMl:bqdfxtn) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Please note the usage of `numactl --cpubind=0 --membind=0` in this command. So this is executing the command only on node 0. On a 36 cores system, the number of logical cores available to run this command will be 36 if hyperthreading is disabled and 72 if hyperthreading is enabled. The best performance can be achieved if we run 36 threads if hyperthreading is disabled and 72 threads if hyperthreading is enabled. Hence the THREAD_CNT is calculated as `Core(s) per socket * Thread(s) per core`. As per the command it is using all the allocated CPUs.
</blockquote></details>

Then you should write "logical cores on the socket 0", that's the number you want here. Also, could you make it clear that this example is utilizing _only socket0_? This is quite important and I missed this when reading the current version.


<!-- Sent from Reviewable.io -->

2022-02-16 06:12 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: 5 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[openvino/README.md, line 42 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcg58gB6GMxhBwTIL-:-Mw09LSh2WFH-2CjSjwJ:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then you should write "logical cores on the socket 0", that's the number you want here. Also, could you make it clear that this example is utilizing _only socket0_? This is quite important and I missed this when reading the current version.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-16 13:23 UTC, mkow requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[openvino/README.md, line 46 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcfv_l4aCZoQ_FJm4j:-Mw1gsxM4GwpFZIn-_fP:bdvw8ud) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L46)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Here the optimal value for best performance is found as the number of logical cores in one socket. Even if HT disabled Thread(s) per core will be 1. So this calculation seems fine.
</blockquote></details>

What about here?
___
*[openvino/README.md, line 78 at r6](https://reviewable.io/reviews/gramineproject/examples/6#-Mvd1D-R00Aozs4kTf2S:-Mw1gv086zq1i8QC2104:b-1kzc8v) ([raw file](https://github.com/gramineproject/examples/blob/ac3ca93329cc29d7ff62799617b3eab8b435cef7/openvino/README.md#L78)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Here the optimal value for best performance is found as the number of logical cores in one socket. Even if HT is disabled Thread(s) per core will be 1. So this calculation seems fine.
</blockquote></details>

And here?


<!-- Sent from Reviewable.io -->

2022-02-16 13:52 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[openvino/README.md, line 46 at r5](https://reviewable.io/reviews/gramineproject/examples/6#-Mtcfv_l4aCZoQ_FJm4j:-Mw1naNmE0Hlg1woOroC:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/3f98b69396d6839f2b9b0cad81cded4b58f4e013/openvino/README.md#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about here?
</blockquote></details>

Done.
___
*[openvino/README.md, line 78 at r6](https://reviewable.io/reviews/gramineproject/examples/6#-Mvd1D-R00Aozs4kTf2S:-Mw1ncWZ3MSvBp_GzZiN:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/ac3ca93329cc29d7ff62799617b3eab8b435cef7/openvino/README.md#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

And here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-16 14:21 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2022-02-17 07:33 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[openvino/benchmark_app.manifest.template, line 1 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5_W5tCP4dtVLrFj_e:-Mw5_W5tCP4dtVLrFj_f:b-f1ra67) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/benchmark_app.manifest.template#L1)):*
> ```
> loader.preload = "file:{{ gramine.libos }}"
> ```

TODO(myself): add `pal.entrypoint` and mark this preload option as "for compatibility"
___
*[openvino/benchmark_app.manifest.template, line 35 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5_dMd5f3cYkcoYOPl:-Mw5_dMd5f3cYkcoYOPm:bh5msvg) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/benchmark_app.manifest.template#L35)):*
> ```
> 
> sgx.preheat_enclave = true
> loader.insecure__use_cmdline_argv = true
> ```

TODO(myself): separate this visible from other options (move up)
___
*[openvino/Makefile, line 11 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5_j8t5sgnUWNLY0nW:-Mw5_j8t5sgnUWNLY0nX:b-h63f8r) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/Makefile#L11)):*
> ```Makefile
> INFERENCE_ENGINE_CPP_SAMPLES_BUILD ?= $(THIS_DIR)inference_engine_cpp_samples_build
> 
> MODEL_DIR ?= $(THIS_DIR)model
> ```

TODO(myself): add `/` for readability
___
*[openvino/README.md, line 33 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5a2YR2gmJhXoKsmbU:-Mw5a2YR2gmJhXoKsmbV:b-nzxenf) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/README.md#L33)):*
> ```Markdown
> 1. Set up OpenVINO environment variables by running:
>     - root user: `source /opt/intel/openvino_2021/bin/setupvars.sh`
>     - root user and set permanently: Append `source /opt/intel/openvino_2021/bin/setupvars.sh` to `~/.bashrc`
> ```

TODO(myself): `Append` -> `append`
___
*[openvino/README.md, line 44 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5a9Lg6dJMmGgPj5Kc:-Mw5a9LhCTiBwrNG0_TU:b-307hez) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/README.md#L44)):*
> ```Markdown
> 
> Options `-nireq`, `-nstreams` and `-nthreads` should be set to the
> `number of logical cores on the socket 0` for achieving maximum performance.
> ```

TODO(myself): remove backticks, this is just normal text. Maybe use italics.
___
*[openvino/README.md, line 71 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5aENBCQCmOodmBt0y:-Mw5aENBCQCmOodmBt0z:bjsyvj4) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/README.md#L71)):*
> ```Markdown
> 
> To run the benchmark natively (outside Gramine), replace `gramine-sgx benchmark_app`
> with `./benchmark_app` in the above command.
> ```

TODO(myself): Add a similar sentence to run with `gramine-direct`. Maybe under a separate subsection.


<!-- Sent from Reviewable.io -->

2022-02-17 07:51 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[-- commits, line 4 at r2](https://reviewable.io/reviews/gramineproject/examples/6#-Mpp5OAu8dQCvYYRsM55):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done
___
*[openvino/benchmark_app.manifest.template, line 1 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5_W5tCP4dtVLrFj_e:-Mw5bb-d1FKvdCSwXGpN:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/benchmark_app.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): add `pal.entrypoint` and mark this preload option as "for compatibility"
</blockquote></details>

Done
___
*[openvino/benchmark_app.manifest.template, line 35 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5_dMd5f3cYkcoYOPl:-Mw5bc8ZD3oRvoyx21G-:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/benchmark_app.manifest.template#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): separate this visible from other options (move up)
</blockquote></details>

Done
___
*[openvino/Makefile, line 11 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5_j8t5sgnUWNLY0nW:-Mw5bg7ZA1XC0Orn4mma:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/Makefile#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): add `/` for readability
</blockquote></details>

Done
___
*[openvino/README.md, line 33 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5a2YR2gmJhXoKsmbU:-Mw5cCk15ay4-VFI_vbq:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/README.md#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): `Append` -> `append`
</blockquote></details>

Done
___
*[openvino/README.md, line 44 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5a9Lg6dJMmGgPj5Kc:-Mw5cDYZ4vxonESSuk_4:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/README.md#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): remove backticks, this is just normal text. Maybe use italics.
</blockquote></details>

Done
___
*[openvino/README.md, line 71 at r9](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5aENBCQCmOodmBt0y:-Mw5cEM99W0_QR5VDuGg:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/e2bd602d71c9a1667e049084d044ae2b98775b89/openvino/README.md#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): Add a similar sentence to run with `gramine-direct`. Maybe under a separate subsection.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-02-17 07:52 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5edfVD1XeQTPExHAI:-Mw5edfVD1XeQTPExHAJ:bvhc3er) (no related file):*
@sahason I rebased this PR to the latest master. It is ready to merge. Could you please verify that this version is still correct? Could you please verify that OpenVINO builds and runs fine with Gramine v1.1 release?

---


<!-- Sent from Reviewable.io -->

2022-02-17 10:05 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dmitrii and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5edfVD1XeQTPExHAI:-Mw67Ln-72kPJDgrhT9t:b8kvbys) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason I rebased this PR to the latest master. It is ready to merge. Could you please verify that this version is still correct? Could you please verify that OpenVINO builds and runs fine with Gramine v1.1 release?
</blockquote></details>

Thanks Dmitrii. I have verified that OpenVINO builds and runs fine with the Gramine v1.1 release and the version is correct. Please go ahead and merge. Thank you Dmitrii, @mkow for your input. 

---


<!-- Sent from Reviewable.io -->

2022-02-17 10:09 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/6#-Mw5edfVD1XeQTPExHAI:-Mw692-D-ybpjRRWWhQB:bb90mz5) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Thanks Dmitrii. I have verified that OpenVINO builds and runs fine with the Gramine v1.1 release and the version is correct. Please go ahead and merge. Thank you @Dmitrii, @mkow for your input. 
</blockquote></details>

Thanks! Approving.

---


<!-- Sent from Reviewable.io -->

2022-02-17 13:12 UTC, mkow approved these changes
> Reviewed 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/6)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-17 14:02 UTC, merged