Add missing license notices
gramineproject/examples pull request #64
Opened 2023-04-25 12:40 UTC by mkow

Seems we forgot to migrate the license notices when moving these examples out of the main repo.

Fixes #62.

2023-04-25 13:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[`LICENSE.txt` line 97 at r1](https://reviewable.io/reviews/gramineproject/examples/64#-NTsQf7uB-KyWo-toA0X:-NTsTDtU2EIh1VyClAji:bb74toy) ([raw file](https://github.com/gramineproject/examples/blob/e3f9f248b5ce5be5b39df711adf6b6e934116688/LICENSE.txt#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Something is wrong with this file -- tabs are weird.
</blockquote></details>

That's true, but it's a 1-1 binary copy from `gramine` repo, it's also broken there. It was added 6 years ago in a PR you probably don't want to read for your sanity... (https://github.com/gramineproject/graphene/pull/140/commits).

Should I download LGPL license from some sane source and fix it here and in other repos?
___
*[`curl/curl.manifest.template` line 1 at r1](https://reviewable.io/reviews/gramineproject/examples/64#-NTsQn5V5RbOdLTVaWyG:-NTsVp-P2ZJLgiVnWZxZ:b-77h3vr) ([raw file](https://github.com/gramineproject/examples/blob/e3f9f248b5ce5be5b39df711adf6b6e934116688/curl/curl.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But we don't have this on manifest-templates and Makefiles in the core repo. Why do we need it here?

Isn't the LICENSE file at the root dir enough?
</blockquote></details>

Technically it is, but having it here makes it less error prone when people move these files between repos (especially for examples, which are likely to be copied outside Gramine by users).
___
*[`openjdk/MultiThreadMain.java` line 1 at r1](https://reviewable.io/reviews/gramineproject/examples/64#-NTsQxOY9OzcqmDT7TBl:-NTsWBH66NdE17CWuJnM:b-f42uhn) ([raw file](https://github.com/gramineproject/examples/blob/e3f9f248b5ce5be5b39df711adf6b6e934116688/openjdk/MultiThreadMain.java#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`//` -> `#`
</blockquote></details>

But this is Java?


<!-- Sent from Reviewable.io -->

2023-04-25 13:24 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[`LICENSE.txt` line 97 at r1](https://reviewable.io/reviews/gramineproject/examples/64#-NTsQf7uB-KyWo-toA0X:-NTs_OIn8B3UHk_T8y2x:b1k3ip4) ([raw file](https://github.com/gramineproject/examples/blob/e3f9f248b5ce5be5b39df711adf6b6e934116688/LICENSE.txt#L97)):*
> It was added 6 years ago in a PR you probably don't want to read for your sanity...

`+1,012 −861,203`

Oh yes, those days.

> Should I download LGPL license from some sane source and fix it here and in other repos?

Yes, please, or I can do it. This is embarassing.
___
*[`curl/curl.manifest.template` line 1 at r1](https://reviewable.io/reviews/gramineproject/examples/64#-NTsQn5V5RbOdLTVaWyG:-NTs_Ygo7RaBNpJzAymy:bxkaqjp) ([raw file](https://github.com/gramineproject/examples/blob/e3f9f248b5ce5be5b39df711adf6b6e934116688/curl/curl.manifest.template#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Technically it is, but having it here makes it less error prone when people move these files between repos (especially for examples, which are likely to be copied outside Gramine by users).
</blockquote></details>

Ah, ok, this last point in the brackets is fair enough.
___
*[`openjdk/MultiThreadMain.java` line 1 at r1](https://reviewable.io/reviews/gramineproject/examples/64#-NTsQxOY9OzcqmDT7TBl:-NTs_dLECVfu9Zr3vriu:bb31bk) ([raw file](https://github.com/gramineproject/examples/blob/e3f9f248b5ce5be5b39df711adf6b6e934116688/openjdk/MultiThreadMain.java#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this is Java?
</blockquote></details>

Lol, resolved


<!-- Sent from Reviewable.io -->

2023-04-25 13:43 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: 24 of 25 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`LICENSE.txt` line 97 at r1](https://reviewable.io/reviews/gramineproject/examples/64#-NTsQf7uB-KyWo-toA0X:-NTsd_nsDcdZD2zgbafM:b80b5xq) ([raw file](https://github.com/gramineproject/examples/blob/e3f9f248b5ce5be5b39df711adf6b6e934116688/LICENSE.txt#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> It was added 6 years ago in a PR you probably don't want to read for your sanity...

`+1,012 −861,203`

Oh yes, those days.

> Should I download LGPL license from some sane source and fix it here and in other repos?

Yes, please, or I can do it. This is embarassing.
</blockquote></details>

I replaced it with https://www.gnu.org/licenses/lgpl-3.0.txt. It still has a bit weird line hard wrapping, but much better than before. If it looks good then I'll do the same in the main repo.


<!-- Sent from Reviewable.io -->

2023-04-25 13:54 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-26 09:40 UTC, kailun-qin requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`r/scripts/sample.r` line 1 at r2](https://reviewable.io/reviews/gramineproject/examples/64#-NTwvaXXCt_7MtVc1Qh-:-NTwvaXXCt_7MtVc1Qh0:bvgtdzf) ([raw file](https://github.com/gramineproject/examples/blob/9b8055818235e618bd5c656d1f15ceb2e127e0f1/r/scripts/sample.r#L1)):*
> ```Rebol
> # SPDX-License-Identifier: LGPL-3.0-or-later
> ```

This seems to be from https://www.rexamples.com/14/Sample() -- do we want to add some notes here?


<!-- Sent from Reviewable.io -->

2023-04-26 11:58 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: 24 of 25 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`r/scripts/sample.r` line 1 at r2](https://reviewable.io/reviews/gramineproject/examples/64#-NTwvaXXCt_7MtVc1Qh-:-NTxPxfI92vOmhXjTgXS:b-jisx0g) ([raw file](https://github.com/gramineproject/examples/blob/9b8055818235e618bd5c656d1f15ceb2e127e0f1/r/scripts/sample.r#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

This seems to be from https://www.rexamples.com/14/Sample() -- do we want to add some notes here?
</blockquote></details>

Huh, I didn't expect that someone copied these 5 lines from somewhere instead of just writing them :) But good catch, fixed.


<!-- Sent from Reviewable.io -->

2023-04-26 13:23 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: 24 of 25 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-04-26 13:31 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-26 13:33 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: 22 of 25 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-04-26 13:37 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/64)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/64#-NTxm-p_0XqrJXaJYf5W:-NTxm-paAagzUx97G3vE:bw4da36) (no related file):*
FYI: I did several quick sanity tests to make sure that these license notices didn't break anything (e.g., because the comments are put in incorrect style or at incorrect places). Looks good.

___


<!-- Sent from Reviewable.io -->

2023-04-26 13:38 UTC, merged