Update Scikit-learn manifest template
gramineproject/examples pull request #70
Opened 2023-05-08 10:45 UTC by anjalirai-intel

Scikit depends on pandas which rely on pytz library, pytz installed by apt requires timezone info to be mounted

2023-05-08 12:16 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/70)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @anjalirai-intel)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/examples/70#-NUvGMiUAB-jJR6v6bO8):*
Better wording (I can fix during final rebase):
```
Scikit depends on pandas which in turn relies on the pytz library.
The newer pytz versions require timezone info to be mounted.
```
___
*[`scikit-learn-intelex/sklearnex.manifest.template` line 37 at r1](https://reviewable.io/reviews/gramineproject/examples/70#-NUvHMQP0pCjX4UgDpxR:-NUvHMQP0pCjX4UgDpxS:bmhjr4o) ([raw file](https://github.com/gramineproject/examples/blob/7b1f3b63b0b78eda357dfb66b54632e7dfa0c31c/scikit-learn-intelex/sklearnex.manifest.template#L37)):*
> ```
>   { path = "/home/user/.local/lib", uri = "file:{{ env.HOME }}/.local/lib" },
> 
>   { type = "tmpfs", path = "/tmp" },
> ```

Please move this entry to be the very last one. This is simply for readability.
___
*[`scikit-learn-intelex/sklearnex.manifest.template` line 41 at r1](https://reviewable.io/reviews/gramineproject/examples/70#-NUvGk3l9_jDWs-vH3H0:-NUvGk3l9_jDWs-vH3H1:br6hdgp) ([raw file](https://github.com/gramineproject/examples/blob/7b1f3b63b0b78eda357dfb66b54632e7dfa0c31c/scikit-learn-intelex/sklearnex.manifest.template#L41)):*
> ```
>   # scikit import pandas, pandas rely on pytz library, pytz installed by apt fails if it
>   # does not finds /usr/share/zoneinfo, # (this was found on pytz version # 2022.1
>   # installed by apt)
> ```

Please change to this:
```
  # Scikit imports pandas which in turn relies on the pytz library. The newer pytz versions fail if
  # cannot find files under /usr/share/zoneinfo (found on pytz version 2022.1, installed by apt).
```
___
*[`scikit-learn-intelex/sklearnex.manifest.template` line 61 at r1](https://reviewable.io/reviews/gramineproject/examples/70#-NUvHS6fCzMIzq5GQRXJ:-NUvHS6gAgtrTfMN0f0p:b-21i82f) ([raw file](https://github.com/gramineproject/examples/blob/7b1f3b63b0b78eda357dfb66b54632e7dfa0c31c/scikit-learn-intelex/sklearnex.manifest.template#L61)):*
> ```
>   "file:data/",
>   "file:scripts/",
>   "file:/usr/share/zoneinfo/"
> ```

Please add a `,` at the end of this line -- this is better when rearranging or appending more items to this list in the future.


<!-- Sent from Reviewable.io -->

2023-05-09 05:21 UTC, anjalirai-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/70)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/gramineproject/examples/70#-NUvGMiUAB-jJR6v6bO8):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Better wording (I can fix during final rebase):
```
Scikit depends on pandas which in turn relies on the pytz library.
The newer pytz versions require timezone info to be mounted.
```
</blockquote></details>

Done
___
*[`scikit-learn-intelex/sklearnex.manifest.template` line 37 at r1](https://reviewable.io/reviews/gramineproject/examples/70#-NUvHMQP0pCjX4UgDpxR:-NUyx2xMD3EReHC7r6NT:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/7b1f3b63b0b78eda357dfb66b54632e7dfa0c31c/scikit-learn-intelex/sklearnex.manifest.template#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move this entry to be the very last one. This is simply for readability.
</blockquote></details>

Done
___
*[`scikit-learn-intelex/sklearnex.manifest.template` line 41 at r1](https://reviewable.io/reviews/gramineproject/examples/70#-NUvGk3l9_jDWs-vH3H0:-NUyx5S94VmI-szJ3zna:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/7b1f3b63b0b78eda357dfb66b54632e7dfa0c31c/scikit-learn-intelex/sklearnex.manifest.template#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please change to this:
```
  # Scikit imports pandas which in turn relies on the pytz library. The newer pytz versions fail if
  # cannot find files under /usr/share/zoneinfo (found on pytz version 2022.1, installed by apt).
```
</blockquote></details>

Done
___
*[`scikit-learn-intelex/sklearnex.manifest.template` line 61 at r1](https://reviewable.io/reviews/gramineproject/examples/70#-NUvHS6fCzMIzq5GQRXJ:-NUyx7gH6rPszpnFS0tm:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/7b1f3b63b0b78eda357dfb66b54632e7dfa0c31c/scikit-learn-intelex/sklearnex.manifest.template#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a `,` at the end of this line -- this is better when rearranging or appending more items to this list in the future.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-05-09 06:10 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/70)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-05-09 11:45 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/70)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-07-10 15:35 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/70)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @anjalirai-intel)

___
*[`scikit-learn-intelex/sklearnex.manifest.template` line 38 at r2](https://reviewable.io/reviews/gramineproject/examples/70#-N_-QqTK7gk7yDLUp7ai:-N_-QqTK7gk7yDLUp7aj:b-xorih6) ([raw file](https://github.com/gramineproject/examples/blob/040bd535d9d999eabd893cc13d2efa7b764e8b11/scikit-learn-intelex/sklearnex.manifest.template#L38)):*
> ```
> 
>   # Scikit imports pandas which in turn relies on the pytz library. The newer pytz versions fail if
>   # cannot find files under /usr/share/zoneinfo (found on pytz version 2022.1, installed by apt).
> ```

`fail if cannot find` -> `fail if they cannot find`


<!-- Sent from Reviewable.io -->

2023-07-10 17:07 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/70)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`scikit-learn-intelex/sklearnex.manifest.template` line 38 at r2](https://reviewable.io/reviews/gramineproject/examples/70#-N_-QqTK7gk7yDLUp7ai:-N_-lM5K5yBIIC5TxciN:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/040bd535d9d999eabd893cc13d2efa7b764e8b11/scikit-learn-intelex/sklearnex.manifest.template#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`fail if cannot find` -> `fail if they cannot find`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-07-10 17:22 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/70)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-07-10 22:38 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/70)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-11 01:13 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/70)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-11 06:34 UTC, merged