Add iperf example
gramineproject/examples pull request #87
Opened 2024-01-12 23:01 UTC by dimstav23

This PR adds the `iperf` example.
It provides a `Makefile` that clones and builds the latest stable version (3.16) of `iperf` as of now.
Note that it places the `iperf3` executable and the `libiperf` shared library in the created `install` directory.
It further includes the Gramine manifest template and a top level README that provides instructions on how to compile and run the `iperf` server (both natively and in Gramine --- with and without SGX) and the `iperf` client (natively) to get the desired measurements.

2024-01-19 08:09 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimstav23)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/87#-NoVl70X7IgxfS6U29AU:-NoVl70X7IgxfS6U29AV:b-selpm6) (no related file):*
Add the explicit BSD-3 license, see https://github.com/gramineproject/examples/pull/90

___


<!-- Sent from Reviewable.io -->

2024-01-19 09:06 UTC, dimstav23 commented
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)_ status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimstav23)
> 
> _[a discussion](https://reviewable.io/reviews/gramineproject/examples/87#-NoVl70X7IgxfS6U29AU:-NoVl70X7IgxfS6U29AV:b-selpm6) (no related file):_ Add the explicit BSD-3 license, see #90

Added the BSD-3 licence.

2024-01-19 09:10 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimstav23)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/87#-NoVl70X7IgxfS6U29AU:-NoVz5R8BMX0qP2u9_Cq:b-zcjvte) (no related file):*
<details><summary><i>Previously, dimstav23 (Dimitris) wrote…</i></summary><blockquote>

Added the BSD-3 license.
</blockquote></details>

Thanks

___


<!-- Sent from Reviewable.io -->

2024-01-24 21:59 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @dimstav23)

___
*[`iperf/Makefile` line 21 at r3](https://reviewable.io/reviews/gramineproject/examples/87#-NoBLEds66zSlKs8Vqz0:-NoxSFwV-kIlrPc2xE2X:bxwdtvt) ([raw file](https://github.com/gramineproject/examples/blob/20922fe02b6732c79fe59c2856d43a544c38a8e3/iperf/Makefile#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Other reviewers: please note that here we use `git clone && git checkout <tag>`. I don't remember if there are any objections against this way of downloading the code?

Alternatively, we can easily replace with a classic "download from GitHub Releases page".
</blockquote></details>

Tags are as mutable as branches, both are just refs in git. Of course this is vulnerable to anyone capable of pushing to the repo of mitming HTTPS. Unless you're verifying signature over either tag or commit, which you're not, you should be checking out SHA1. Code as it is here is bad example.

But this is all unneeded. Why can't we just use iperf or iperf3 installed from distro packages?


<!-- Sent from Reviewable.io -->

2024-01-25 10:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @dimstav23)

___
*[`iperf/Makefile` line 21 at r3](https://reviewable.io/reviews/gramineproject/examples/87#-NoBLEds66zSlKs8Vqz0:-Np-3tSH3IhB592NefAM:bxr43ju) ([raw file](https://github.com/gramineproject/examples/blob/20922fe02b6732c79fe59c2856d43a544c38a8e3/iperf/Makefile#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Tags are as mutable as branches, both are just refs in git. Of course this is vulnerable to anyone capable of pushing to the repo of mitming HTTPS. Unless you're verifying signature over either tag or commit, which you're not, you should be checking out SHA1. Code as it is here is bad example.

But this is all unneeded. Why can't we just use iperf or iperf3 installed from distro packages?
</blockquote></details>

I will take care of this now.

But I want to do it via "download from GitHub Releases page". I think it's much better to have a specific version of the tool, instead of the unknown distro package version.


<!-- Sent from Reviewable.io -->

2024-01-25 10:17 UTC, dimstav23 commented
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)_ status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @dimstav23)
> 
> _[`iperf/Makefile` line 21 at r3](https://reviewable.io/reviews/gramineproject/examples/87#-NoBLEds66zSlKs8Vqz0:-Np-3tSH3IhB592NefAM:bxr43ju) ([raw file](https://github.com/gramineproject/examples/blob/20922fe02b6732c79fe59c2856d43a544c38a8e3/iperf/Makefile#L21)):_
> 
> Previously, woju (Wojtek Porczyk) wrote…
> I will take care of this now.
> 
> But I want to do it via "download from GitHub Releases page". I think it's much better to have a specific version of the tool, instead of the unknown distro package version.

I also tried to adapt it to use the Ubuntu 22.04.3 LTS package binary. 
However I hit on [this error](https://github.com/gramineproject/graphene/issues/1658).
Note: tested with `gramine-direct` using `gramine v1.6`

2024-01-25 10:19 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimstav23 and @woju)

___
*[`iperf/Makefile` line 21 at r3](https://reviewable.io/reviews/gramineproject/examples/87#-NoBLEds66zSlKs8Vqz0:-Np-7Fzu8w4tfq8WBjpS:byuvbzl) ([raw file](https://github.com/gramineproject/examples/blob/20922fe02b6732c79fe59c2856d43a544c38a8e3/iperf/Makefile#L21)):*
<details><summary><i>Previously, dimstav23 (Dimitris) wrote…</i></summary><blockquote>

I also tried to adapt it to use the Ubuntu 22.04.3 LTS package binary. 
However I hit on [this error](https://github.com/gramineproject/graphene/issues/1658).
Note: tested with `gramine-direct` using `gramine v1.6`.

</blockquote></details>

Thanks @dimstav23 for explanations.

Anyway, done now.


<!-- Sent from Reviewable.io -->

2024-01-25 16:12 UTC, woju reviewed
> Reviewed 1 of 2 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimstav23)

___
*[`iperf/Makefile` line 21 at r3](https://reviewable.io/reviews/gramineproject/examples/87#-NoBLEds66zSlKs8Vqz0:-Np0NCGp9j_Ged67koFr:b-2oem89) ([raw file](https://github.com/gramineproject/examples/blob/20922fe02b6732c79fe59c2856d43a544c38a8e3/iperf/Makefile#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks @dimstav23 for explanations.

Anyway, done now.
</blockquote></details>

Ah, yes, if there's technical reason, then OK, but please describe the problem in README and say that for iperf3 to work in Gramine, you need to recompile it to disable usage of that flag. What I want to avoid is people who will use iperf from distro rediscovering this problem the hard way.


<!-- Sent from Reviewable.io -->

2024-01-26 07:59 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimstav23)

___
*[`iperf/Makefile` line 21 at r3](https://reviewable.io/reviews/gramineproject/examples/87#-NoBLEds66zSlKs8Vqz0:-Np3lmoR-ITJ_1lSyL3k:b-te7xeq) ([raw file](https://github.com/gramineproject/examples/blob/20922fe02b6732c79fe59c2856d43a544c38a8e3/iperf/Makefile#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Ah, yes, if there's technical reason, then OK, but please describe the problem in README and say that for iperf3 to work in Gramine, you need to recompile it to disable usage of that flag. What I want to avoid is people who will use iperf from distro rediscovering this problem the hard way.
</blockquote></details>

Done.

It got even more interesting. This same problem was hit on Microsoft's WSL, so iperf authors fixed it in v3.10:
- https://github.com/esnet/iperf/issues/1061
- https://github.com/esnet/iperf/pull/1126
- https://github.com/esnet/iperf/blob/master/RELNOTES.md#iperf-310-2021-05-26

On Ubuntu 22.04, however, we have v3.9: https://packages.ubuntu.com/jammy/iperf3


<!-- Sent from Reviewable.io -->

2024-01-26 09:37 UTC, kailun-qin requested changes
> Reviewed 1 of 2 files at r5, 1 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimstav23)

___
*[`iperf/README.md` line 9 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np3yrc9EMioP_2DhOXF:-Np3yrcAEby5iowyib7h:bhjje3d) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L9)):*
> ```Markdown
> 
> `iperf` has no prerequisites
> ([source](https://github.com/esnet/iperf?tab=readme-ov-file#prerequisites)).
> ```

Can we pin this to a specific commit/tag?



_Code quote:_
```Markdown
https://github.com/esnet/iperf?tab=readme-ov-file#prerequisites
```
___
*[`iperf/README.md` line 14 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np3z8Vj9eOwhVGmvV6t:-Np3z8Vj9eOwhVGmvV6u:b-k2hvk1) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L14)):*
> ```Markdown
> 
> We build `iperf` from source because on current Ubuntu distros (we tested Ubuntu
> 22.04), the `iperf3` package has a version 3.9 which is built with
> ```

why not simply -> `...because Ubuntu 22.04 has `iperf3` v3.9 in its package repositories which is built ...`



_Code quote:_
```Markdown
We build `iperf` from source because on current Ubuntu distros (we tested Ubuntu
22.04), the `iperf3` package has a version 3.9 which is built with
```
___
*[`iperf/README.md` line 27 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np4-M608SdLqGmdVOeA:-Np4-M608SdLqGmdVOeB:bynmova) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L27)):*
> ```Markdown
> implement congestion control algorithm. Thus, iperf 3.10+ prebuilt packages
> should work under Gramine without problems. See [release
> notes](https://github.com/esnet/iperf/blob/master/RELNOTES.md#iperf-310-2021-05-26)
> ```

ditto (pin to specific commit/tag)



_Code quote:_
```Markdown
https://github.com/esnet/iperf/blob/master/RELNOTES.md#iperf-310-2021-05-26
```
___
*[`iperf/README.md` line 33 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np4-WhE6LSX2sY_vAYC:-Np4-WhE6LSX2sY_vAYD:b-pbkw0l) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L33)):*
> ```Markdown
> ## Building for Linux
> 
> Run `make` in the root directory.
> ```

current?



_Code quote:_
```Markdown
root
```
___
*[`iperf/README.md` line 37 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np4-Yg8DDiFDUIsPbk9:-Np4-Yg8DDiFDUIsPbkA:b-7ropln) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L37)):*
> ```Markdown
> ## Building for SGX
> 
> Run `make SGX=1` (non-debug) or `make SGX=1 DEBUG=1` (debug) in the root
> ```

ditto



_Code quote:_
```Markdown
root
```
___
*[`iperf/README.md` line 72 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np475mCB4pJJ8JLDvSG:-Np475mCB4pJJ8JLDvSH:bop32mc) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L72)):*
> ```Markdown
> - `-s, --server`: run in server mode
> - `-1, --one-off`: handle one client connection then exit
> - `--idle-timeout #`: restart idle server after # seconds in case it got stuck
> ```

The option(s) here may also be version-dependent. I suggest that we also note this somewhere.



_Code quote:_
```Markdown
--idle-timeout
```


<!-- Sent from Reviewable.io -->

2024-01-26 15:16 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 4 at r8](https://reviewable.io/reviews/gramineproject/examples/87#-Np5L0M_DlbSgWluaa7M):*
TODO: Add myself as co-author.
___
*[`iperf/README.md` line 9 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np3yrc9EMioP_2DhOXF:-Np5K5DdEiQ7UqAlZVjt:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Can we pin this to a specific commit/tag?
</blockquote></details>

Done
___
*[`iperf/README.md` line 14 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np3z8Vj9eOwhVGmvV6t:-Np5KJ-wDAn_GVbRkFlP:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L14)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

why not simply -> `...because Ubuntu 22.04 has `iperf3` v3.9 in its package repositories which is built ...`
</blockquote></details>

Done
___
*[`iperf/README.md` line 27 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np4-M608SdLqGmdVOeA:-Np5KRVM0nYE-QxGTfIs:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L27)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto (pin to specific commit/tag)
</blockquote></details>

Done
___
*[`iperf/README.md` line 33 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np4-WhE6LSX2sY_vAYC:-Np5KVNu7HHLnnSNqEgu:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L33)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

current?
</blockquote></details>

Done
___
*[`iperf/README.md` line 37 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np4-Yg8DDiFDUIsPbk9:-Np5KWo7BgWYy-kAbMND:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L37)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[`iperf/README.md` line 72 at r7](https://reviewable.io/reviews/gramineproject/examples/87#-Np475mCB4pJJ8JLDvSG:-Np5Keb_0jwGDw8nHrWK:bb6un1j) ([raw file](https://github.com/gramineproject/examples/blob/1a406d633b11d2feb969c8e1debdfa4abde30727/iperf/README.md#L72)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

The option(s) here may also be version-dependent. I suggest that we also note this somewhere.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-26 15:22 UTC, woju approved these changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`iperf/Makefile` line 21 at r3](https://reviewable.io/reviews/gramineproject/examples/87#-NoBLEds66zSlKs8Vqz0:-Np5L0NQ9fA5EwZBGFgW:bknv9gx) ([raw file](https://github.com/gramineproject/examples/blob/20922fe02b6732c79fe59c2856d43a544c38a8e3/iperf/Makefile#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

It got even more interesting. This same problem was hit on Microsoft's WSL, so iperf authors fixed it in v3.10:
- https://github.com/esnet/iperf/issues/1061
- https://github.com/esnet/iperf/pull/1126
- https://github.com/esnet/iperf/blob/master/RELNOTES.md#iperf-310-2021-05-26

On Ubuntu 22.04, however, we have v3.9: https://packages.ubuntu.com/jammy/iperf3
</blockquote></details>

Debian 12 has 3.12 and Ubuntu 24.04 will have at least 3.15 (which is what's in `noble` right now: https://launchpad.net/ubuntu/+source/iperf3. So IDK, either you merge as is with a TODO bug filed to be fixed after 24.04, or you can test on `bookworm` or `mantic` (23.10) and just write that in README. I'm OK with either case.


<!-- Sent from Reviewable.io -->

2024-01-26 15:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`iperf/Makefile` line 21 at r3](https://reviewable.io/reviews/gramineproject/examples/87#-NoBLEds66zSlKs8Vqz0:-Np5NYzLAcGPPsmpcWbl:bzi4ulb) ([raw file](https://github.com/gramineproject/examples/blob/20922fe02b6732c79fe59c2856d43a544c38a8e3/iperf/Makefile#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Debian 12 has 3.12 and Ubuntu 24.04 will have at least 3.15 (which is what's in `noble` right now: https://launchpad.net/ubuntu/+source/iperf3. So IDK, either you merge as is with a TODO bug filed to be fixed after 24.04, or you can test on `bookworm` or `mantic` (23.10) and just write that in README. I'm OK with either case.
</blockquote></details>

Done, added a TODO github issue: https://github.com/gramineproject/examples/issues/92


<!-- Sent from Reviewable.io -->

2024-01-26 15:35 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-01-29 10:37 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/87)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 4 at r8](https://reviewable.io/reviews/gramineproject/examples/87#-Np5L0M_DlbSgWluaa7M):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: Add myself as co-author.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-29 10:40 UTC, merged