Change the license of all examples to BSD-3-clause
gramineproject/examples pull request #90
Opened 2024-01-19 08:09 UTC by dimakuv

The examples had the default license of LGPL-3.0. With this commit, we change the license of all Makefiles, manifest templates, config files, and some scripts in examples to a BSD-3-clause license.

This change is permitted by the "Examples Exception" to the Technical Charter, enacted on 5. December 2023. This change was agreed by all contributors to examples, past and present.

This change is in response to a popular request to adopt a more permissive license for our examples. The new BSD-3-clause is a permissive license (in contrast to the prevoiusly applied copyleft LGPL license). BSD explicitly allows to modify and use our examples without any obligation to share these modifications.

This commit is a counterpart to the commit "[CI-Examples] Add the BSD-3-clause license to all examples" in the core Gramine repo. See https://github.com/gramineproject/gramine/pull/1657.

For details, see also:
- https://github.com/gramineproject/gramine/discussions/1644
- https://github.com/gramineproject/gramine/discussions/1656
- https://github.com/gramineproject/gramine/pull/1670

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/examples/90)

2024-01-19 08:22 UTC, kailun-qin requested changes
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/90#-NoVnMFf3bvhO8m1G0Bw):*
Should follow the update of the PR in core Gramine repo



_Code quote:_
```
Add the BSD-3-clause license to all examples
```
___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/gramineproject/examples/90#-NoVnbRt8gGC-mNRZLyZ):*
ditto



_Code quote:_
```
prevoiusly
```
___
*[`LICENSE.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/examples/90#-NoVnJDx99g1MOHBPt33:-NoVnJDy2BsRU_g4g9TY:b-hjw43) ([raw file](https://github.com/gramineproject/examples/blob/402d39439f96877563059ce1be2688a68879eb11/LICENSE.txt#L1)):*
> ```help
> Copyright 2023 GSC Contributors
> ```

-> `Gramine`



_Code quote:_
```help
GSC
```


<!-- Sent from Reviewable.io -->

2024-01-19 08:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/90#-NoVmdmv1bbyJDza9a1x:-NoVmdmv1bbyJDza9a1y:bdhqgwg) (no related file):*
To change the license from LGPL, need acknowledgements from contributors of examples (people who contributed significant changes):

- [x] @dimakuv (myself, I acknowledge)
- [x] @monavij (on behalf of Thomas Knauth, who doesn't work at Intel anymore)
- [x] @vijaydhanraj
- [x] @jkr0103
- [x] @chiache 
- [x] @mkow 
- [ ] @pangzi85480 (aka `jack.wxz`)
- [x] @anjalirai-intel

The list is partially taken from this first commit: https://github.com/gramineproject/examples/commit/f55dc0da998580094bff9fbfbcb220fdb55bae9f. And by manually inspecting other commits.

___


<!-- Sent from Reviewable.io -->

2024-01-19 08:31 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: 26 of 27 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/90#-NoVmdmv1bbyJDza9a1x:-NoVpW7d9vlfbufCDPyv:bhimekl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To change the license from LGPL, need acknowledgements from contributors of examples (people who contributed significant changes):

- [x] @dimakuv (myself, I acknowledge)
- [ ] @monavij (on behalf of Thomas Knauth, who doesn't work at Intel anymore)
- [ ] @vijaydhanraj
- [ ] @jkr0103
- [ ] @chiache 
- [ ] @mkow 
- [ ] @pangzi85480 (aka `jack.wxz`)
- [ ] @anjalirai-intel

The list is partially taken from this first commit: https://github.com/gramineproject/examples/commit/f55dc0da998580094bff9fbfbcb220fdb55bae9f. And by manually inspecting other commits.
</blockquote></details>

All the listed above people (or their managers), could you please acknowledge that you're Ok with having an explicit BSD-3-clause license?

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/examples/90#-NoVnMFf3bvhO8m1G0Bw):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Should follow the update of the PR in core Gramine repo
</blockquote></details>

Done.
___
*[`-- commits` line 14 at r1](https://reviewable.io/reviews/gramineproject/examples/90#-NoVnbRt8gGC-mNRZLyZ):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`LICENSE.txt` line 1 at r1](https://reviewable.io/reviews/gramineproject/examples/90#-NoVnJDx99g1MOHBPt33:-NoVprlA09bg_AUKU3FP:bddi87f) ([raw file](https://github.com/gramineproject/examples/blob/402d39439f96877563059ce1be2688a68879eb11/LICENSE.txt#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

-> `Gramine`
</blockquote></details>

Done. Yeah, copy-paste fail.


<!-- Sent from Reviewable.io -->

2024-01-19 08:33 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-01-19 09:28 UTC, woju approved these changes
> Reviewed 26 of 27 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-01-25 09:51 UTC, mkow requested changes
> Reviewed 26 of 27 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, 4 unresolved discussions (waiting on @anjalirai-intel, @chiache, @dimakuv, @jkr0103, @monavij, @pangzi85480, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/90#-NoVmdmv1bbyJDza9a1x:-Np--3jwCKE6CXSKIZX2:b2nha9w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All the listed above people (or their managers), could you please acknowledge that you're Ok with having an explicit BSD-3-clause license?
</blockquote></details>

ACK

___
___
*[`curl/curl.manifest.template` line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/90#-Np-0tEXBivS9MWekcQc:-Np-0tEXBivS9MWekcQd:b-qd9ftn) ([raw file](https://github.com/gramineproject/examples/blob/1524dc0201ae022a2f8e9b4e6420cd9005ac4254/curl/curl.manifest.template#L2)):*
> ```
> # Copyright (C) 2024 Gramine contributors
> # # SPDX-License-Identifier: BSD-3-Clause
> ```

duplicated `# `
___
*[`curl/Makefile` line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/90#-Np-0GwkEv48xduJ7zdh:-Np-0GwkEv48xduJ7zdi:bs692f9) ([raw file](https://github.com/gramineproject/examples/blob/1524dc0201ae022a2f8e9b4e6420cd9005ac4254/curl/Makefile#L2)):*
> ```Makefile
> # Copyright (C) 2024 Gramine contributors
> # # SPDX-License-Identifier: BSD-3-Clause
> ```

Duplicated `# `


<!-- Sent from Reviewable.io -->

2024-01-25 09:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: 25 of 27 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @chiache, @jkr0103, @kailun-qin, @mkow, @monavij, @pangzi85480, @vijaydhanraj, and @woju)

___
*[`curl/curl.manifest.template` line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/90#-Np-0tEXBivS9MWekcQc:-Np-1a_a7iAeL9f8s699:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/1524dc0201ae022a2f8e9b4e6420cd9005ac4254/curl/curl.manifest.template#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

duplicated `# `
</blockquote></details>

Done.
___
*[`curl/Makefile` line 2 at r2](https://reviewable.io/reviews/gramineproject/examples/90#-Np-0GwkEv48xduJ7zdh:-Np-1ce1-bPpnNVzf2bu:b-896fix) ([raw file](https://github.com/gramineproject/examples/blob/1524dc0201ae022a2f8e9b4e6420cd9005ac4254/curl/Makefile#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Duplicated `# `
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-25 09:59 UTC, jkr0103 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90#-:-Np-2uZG24UlINu3cy7h:bnfp4nl)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @chiache, @monavij, @pangzi85480, and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2024-01-25 10:00 UTC, jkr0103 reviewed
> Reviewed 24 of 27 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @chiache, @monavij, @pangzi85480, and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2024-01-25 10:01 UTC, anjalirai-intel commented
LGTM

2024-01-25 14:09 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @chiache, @monavij, @pangzi85480, and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2024-01-25 16:57 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @chiache, @monavij, and @pangzi85480)

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/90#-NoVmdmv1bbyJDza9a1x:-Np0YXnQEbDPBUwHLehH:b2nha9w) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ACK
</blockquote></details>

ACK

___


<!-- Sent from Reviewable.io -->

2024-02-06 14:31 UTC, chiache approved these changes
> Reviewed 23 of 27 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @monavij, and @pangzi85480)



<!-- Sent from Reviewable.io -->

2024-02-26 08:16 UTC, pangzi85480 commented
LGTM

2024-02-26 08:30 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/examples/90#-NoVmdmv1bbyJDza9a1x:-NrZXFOY5gB-wDex3qF7:bss8yre) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

ACK
</blockquote></details>

All required persons acknowledged the license change, now we can proceed and merge this PR.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/examples/90#-Np--iMi7Hby1hgYkQ51:-NrZXLof79LRojmORm--:b-5d8wtm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@pangzi85480  You contributed to one of the examples in this repository, could you write that you ACK (acknowledge) the change of the license on your example from LGPL to BSD?
</blockquote></details>

Done (see other comment)

___


<!-- Sent from Reviewable.io -->

2024-02-26 08:38 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-26 10:54 UTC, jkr0103 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/examples/90#-:-Nr_2NSc2DU3bDjxtKbL:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-02-26 16:00 UTC, merged